package.json, yarn.lock
**Summary**
Updating Jest to 21, brings some nice perf improvements in initialization time.
**Test plan**
CI pass
=> chore: Update Jest to v21.1.0

src/babel/preval-extract/__tests__/prevalStyles.spec.js, src/babel/preval-extract/prevalStyles.js
**Summary**
This enables us setting custom babel env for server rendering, while staying in `NODE_ENV=production` which calculates hash based on css content instead of filename.
**Test plan**
Updated unit tests.
=> feat: Prefer NODE_ENV before BABEL_ENV

src/server/__tests__/__snapshots__/collect.test.js.snap, src/server/__tests__/collect.test.js, src/server/collect.js
**Summary**
The css from `collect` function in SSR favored `@rules` before normal ones, which resulted in broken CSS order.
**Test plan**
Fixed tests (also running them through `prettier` for readability)
=> fix: Proper ordering of collected CSS

babel.js, package.json, src/babel/hoist-css/__tests__/__snapshots__/index.spec.js.snap, src/babel/hoist-css/__tests__/index.spec.js, src/babel/hoist-css/index.js, src/babel/types.js, yarn.lock
Usually we need to think of a className every time we write some style rules. While this makes sense for rules with well-defined styles, there are many instances where we have a one off rule like `flex: 1` etc. It doesn't make sense to come up with a name for such a rule.
The babel plugin will transpile this:
```js
function MyComponent() {
return <div {...styles(css`flex: 1`)} />;
}
```
to this:
```js
function MyComponent() {
return <div {...styles(_div)} />;
}
var _div = css`flex: 1;`;
```
The plugin also supports `className` and `class` props (for preact) along with `styles`.
Currently we don't support such usage with our babel plugin even if it works fine in runtime, so it looks like it should work in compile time.
More context: #110
=> feat: add a hoist-css plugin. resolves #110

docs/SERVER_RENDERING.md, src/babel/preval-extract/__tests__/extractStyles.spec.js, website/.babelrc, website/.gitignore, website/package.json, website/src/App.js, website/src/components/CodeBlock.js, website/src/index.js, website/src/server.js, website/src/styles/global.css, website/src/styles/global.js, website/src/utils/escapeHtml.js, website/src/utils/prismTemplateString.js, website/static/index.html, website/yarn.lock
**Summary**
Adds server rendering with critical CSS to the website.
Fixes #29 
TODO:
**Test plan**
tbd
=> feat: Setup SSR for website

src/babel/lib/__tests__/errorUtils.spec.js, src/babel/lib/errorUtils.js
**Summary**
This came out while testing Linaria with CRA and Next.js, for some reason (didn't have time to investigate why) `frames` were passed either empty or with undefined object.
**Test plan**
covered
=> fix: guard for first frame in buildCodeFrameError

src/__tests__/index.spec.js
**Summary**
We were missing a test for our public API, so I added one
**Test plan**
CI should be red, waiting for #129 to land
=> chore: add a test for public API

.vscode/settings.json, README.md, website/package.json, website/yarn.lock
**Summary**
This is just a proof of concept, that Linaria works with `typescript-styled-plugin` without additional config. Someday they'll create extensions, but until then we can use this approach.
Added a VS Code config so it's already set up if someone uses it.
=> chore: setup typescript-styled-plugin for vscode on website

benchmark/run.js, benchmark/suites/multiple-deep-external-and-module-dep.js
=> Fix benchmark script

src/babel/__integration-tests__/preval-extract/__snapshots__/errors.spec.js.snap, src/babel/__integration-tests__/preval-extract/with-inline-rules.spec.js, src/babel/preval-extract/__tests__/__snapshots__/index.spec.js.snap, src/babel/preval-extract/__tests__/index.spec.js, src/babel/preval-extract/index.js, src/babel/types.js
This allows to have the template literal inside expressions such as function calls before assigning to a variable.
For example, one could write helper function to generate components with already assigned class names,
```js
const Header = styled('h1', css`
font-weight: bold;
`);
```
=> fix: recursively check for variable declarator

docs/BUNDLERS_INTEGRATION.md
If the user has other loaders that modify the css in his pipeline this will break, e.g. - `url()` with `url-loader` etc. and this will be a production-only bug due to the file being processed by `css-loader` only in development.
=> docs: remove section on single: true from webpack integration

src/babel/lib/__tests__/__snapshots__/moduleSystem.spec.js.snap, src/babel/lib/__tests__/moduleSystem.spec.js, src/babel/lib/moduleSystem.js, src/babel/preval-extract/resolveSource.js
=> Support JSON files and create dummy wrapper module for other non-JS extensions

src/babel/__integration-tests__/preval-extract/exctraction.spec.js, src/babel/preval-extract/extractStyles.js
=> fix: insert relative imports for CSS files and support absolute path in outDir

README.md, src/babel/preval-extract/prevalStyles.js
when the node was generated by another babel plugin, getSource method returns empty string. we can use babel-generator to get the resulting string instead
=> fix: use babel-generator to get the source

README.md, docs/BABEL_PRESET.md, docs/BUNDLERS_INTEGRATION.md, loader.js, package.json, src/tools/webpack-loader.js, website/webpack.config.js, yarn.lock
Fixes #73, #169 
Documentation is missing, but I'll make it once the code will be done.
So the JS rule looks like this:
```js
{
test: /\.js$/,
use: [
{ loader: 'babel-loader', options: { cacheDirectory: true } },
{ loader: 'linaria/loader' }
],
},
```
Then while testing on website:
* changing `theme.js` rebuilds CSS so HMR updates styles
* babel cache is not a problem anymore
* deleting `.linaria-cache` doesn't break anything
=> Webpack loader

src/tools/stylelint-preprocessor.js
`filename` is absolute (from stylelint) but `rawStyles` has relative paths.
Example:
`filename`: `<CWD>/src/App.js`
`rawStyles`: `{ 'src/App.js': { /* ... */ } }`
=> Use relative filename when getting styles in stylelint preprocessor

.circleci/config.yml, docs/LINTING.md, package.json, src/__tests__/__snapshots__/babel.test.js.snap, src/babel/extract.js, src/stylelint/config.js, src/stylelint/preprocessor.js, stylelint-config.js, website/.stylelintrc, website/package.json, website/stylelint.config.js, website/yarn.lock
**How it works**
The Babel plugin returns the unprocessed data in the `metadata` object. The preprocessor takes this data and constructs a CSS string for stylelint to operate on.
**TODO**
=>  feat: add stylelint preprocessor

README.md, src/__tests__/__snapshots__/babel.test.js.snap, src/__tests__/__snapshots__/preval.test.js.snap, src/babel/extract.js, src/react/styled.js, src/stylelint/preprocessor.js
Previously, if you had a `Title = styled.h1` and `Heading = styled(Title)`, and then have the same CSS properties specified in both, the styles which are later in the stylesheet would take precedence. This is one of the limitations we have (had) compared to styled-components. But if we can evaluate expressions at build time, we can get the parent className and generate a more specific selector, ensuring that the correct styles are applied. This PR aims to implement that.
=> feat: apply correct specificity when wrapping a styled component with another

README.md, docs/BABEL_PRESET.md, docs/BUNDLERS_INTEGRATION.md, docs/HOW_IT_WORKS.md, src/babel/extract.js, src/babel/module.js, src/loader.js, src/stylelint/preprocessor.js, src/transform.js, website/babel.config.js, website/webpack.config.js
Linaria's babel plugin won't work properly with babel-loader's cache.
It's better to move it to the loader so that we don't have to disable the cache.
=> fix: move linaria's babel plugin to linaria-loader

src/__tests__/__snapshots__/babel.test.js.snap, src/__tests__/__snapshots__/preval.test.js.snap, src/__utils__/linaria-snapshot-serializer.js, src/babel/extract.js, src/loader.js, src/transform.js
We need to generate sourcemaps when transforming so webpack can show proper sources.
Also moved stylis to the transform helper which would make it not run when evaluating styles and in SSR/test environments, which is unnecessary.
=> fix: fix JS sourcemaps and move stylis out of babel plugin

docs/API.md, src/server/__tests__/__snapshots__/collect.test.js.snap, src/server/__tests__/collect.test.js, src/server/collect.js
For apps using a plugin such as MiniCssExtractPlugin and importing plain CSS files, the global CSS will often be in the same CSS file as the CSS extracted by Linaria. Previously, collect would place these styles in 'other', which would cause a FOUC. There's an undocumented 'globalCSS' argument, but it's not reasonable to manually specify it when you have already imported it in the app.
This PR only checks class name based selectors to determine if they are critical and for all other styles, it will place them in the critical CSS. This handles global CSS without any manual work. This also removes the 'globalCSS' argument because it's not needed anymore.
=> fix: assume non-class name selectors to be critical

src/__tests__/__snapshots__/styled.test.js.snap, src/__tests__/styled.test.js, src/react/styled.js
Say you have 2 components like this:
```js
const First = styled.a`color: blue;`;
const Second = styled(First)`font-size: 14px;`;
<Second as="button" />
```
Previously this would render a `button` with the style `font-size: 14px;`, because the `First` component is swapped for `button`.
This commit changes the behaviour so that if the wrapped tag is a styled component, it'll forward the `as` prop. Which means the resulting styles will now be `color: blue; font-size: 14px;`. It also matches the behaviour of the styled-components library.
=> fix: forward as prop when wrapping another styled component

src/core/css.js, src/react/styled.js, types/index.d.ts, types/tests/react.tsx, types/tsconfig.json, types/tslint.json
Currently we infer the props for the components based on the type of the base component, e.g. - for `styled.button`, it'll be the props of `button`, for `styled(Title)`, it'll be the props of `Title` etc. However, it's common to pass additional props to a styled component specifically for styling. For example:
```js
const Button = styled.button`
background: $(props => props.primary ? 'blue' : 'white'};
`;
```
Here the user needs to pass a `primary` prop even if `button` doesn't accept it. Currently we workaround this by allowing the user to pass any extra props. However, the extra props will be typed as `any`, which is not exactly type checking.
TypeScript has this cool feature of being able to have optional type parameters, which we can use here to allow the user to specify the types …
=> feat: support specifying type of props for styled with TypeScript

package.json
**Summary**
Present Linaria's documentation says that an associated Rollup [plugin](https://github.com/callstack/linaria/blob/master/docs/BUNDLERS_INTEGRATION.md#rollup) can be accessed by the following path: `linaria/rollup`.
Even though this file exists in the repository, it's missing from the npm package, which clearly looks like an oversight. So, this PR adds `rollup.js` to the list of distributed files.
=> fix: add "rollup.js" to the list of distributed files

src/rollup.js
**Summary**
Linaria's plugin for Rollup returns only a modified code of a module, without providing its sourcemaps. This, in turn, leads to a broken source map file and the following warning can be seen when running Rollup with the `sourceMap` option enabled:
```
(!) Broken sourcemap
https://github.com/rollup/rollup/wiki/Troubleshooting#sourcemap-is-likely-to-be-incorrect
Plugins that transform code (such as 'linaria') should generate accompanying sourcemaps
```
This PR ads sourcemaps to the former plugins output, as described in the Rollup's [documentation](https://rollupjs.org/guide/en#transformers).
=> fix: add sourcemaps to the output of Rollup plugin

package.json, src/__tests__/module.test.js, src/babel/module.js, src/loader.js, website/yarn.lock, yarn.lock
I'm using `this._compilation.options` (private and deprecated API) to get access to webpack's resolve options such as `resolve.alias`, `resolve.extensions` etc.
There seems to be no other way to access webpack's resolver. There is `this.resolve`, but it's asynchronous. There was `this.resolveSync`, but it seems to be removed. `this._compilation` is used by many loaders/plugins such as `mini-cssextract-plugin`, so hope we're safe for a while.
Other options are:
1) read the webpack.config.js manually, but it won't work for programmatic usage. `eslint-import-resolver-webpack` does this.
2) require the user to pass the resolve options in the loader options as well. it'll duplicate webpack's config, but won't break.
=> fix: use webpack's resolver to resolve files. fixes #284

docs/BASICS.md, src/__tests__/__snapshots__/babel.test.js.snap, src/__tests__/babel.test.js, website/package.json, website/src/index.js, website/yarn.lock
- This commit upgrade css-loader to 2.1.0 to show how webpack's configuration
should look like for new users who may install the newest version of css-loader
that has breaking change regarding css-modules
More info:
https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#breaking-changes
**Summary**
New users may install css-loader directly like 
```bash
npm install css-loader
yarn add css-loader
```
and these commands will install `css-loader 2.1.0`. Since the `2.x` [css-modules are disabled by default](https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#breaking-changes)
> by default css modules are disabled (now modules: false disable all css modules features), you can return old behaviour change this on modules: 'global'
This commit upgrade css-loader …
=> Chore: Upgrade src/website to use css-loader 2.x

src/loader.js
**Summary**
Adding a semicolon makes code more robust when integrated (concatenated)
with other files
**Test plan**
I tried integrating with [docz](https://github.com/pedronauck/docz) and after I added `linaria/loader` to docz bundler configuration, I got an error like this:
```
Failed to compile.
./src/ui/components/StatementList/NewItemInput/NewItemInput.tsx
SyntaxError: /sample-project/src/ui/components/StatementList/NewItemInput/NewItemInput.tsx: Unexpected token, expected ";" (20:150)
18 | ;
19 |
> 20 | require("/sample-project/.linaria-cache/src/ui/components/StatementList/NewItemInput/NewItemInput.linaria.css")try {
|                                                                                                                ^
21 |     // @ts-ignore
22 | …
```
=> Add semicolon to avoid possible crashes

src/loader.js
In my webpack configuration this._compilation was undefined when running this loader. This also checks if `_compilation` is defined before checking if resolve exists. If not, then falls back to the default options as if resolve is not found.
=> Webpack loader - check if this._compilation is undefined

src/__tests__/transform.test.js, src/babel/evaluate.js
We pass some plugins by default to make evaluation work with ES6 `import` syntax. We also pass the linaria preset during evaluation explicitly. But babel will throw if it encounters duplicate plugins or presets.
This PR adds some filtering to avoid including the same plugins and presets twice.
=> fix: filter out duplicate plugins and prestes when merging babel options

src/__tests__/__snapshots__/babel.test.js.snap, src/__tests__/babel.test.js, src/babel/extract.js
**Summary**
It looks like we do not need to convert keys of nested objects to kebab case because it brakes nested selectors (eg. `'&.camelCaseSelector': {…}` is converted to `&.camel-case-selector {…}`).
**Test plan**
I've added a test for this case.
=> fix: remove redundant `hyphenate` from objects interpolation

src/__tests__/__snapshots__/preval.test.js.snap, src/__tests__/preval.test.js, src/babel/evaluate.js
**Summary**
There is a problem with the evaluation of functions like this
```
const foo = (k) => {
const obj = objects[k];
return obj;
};
```
It will be transformed to
```
{
const foo = k => {
const obj = objects[k];
return obj;
};
{
const obj = objects[k];
{
module.exports = foo('key');
}
}
}
```
As we can see, `obj` was extracted from the function to the global scope.
**Test plan**
A new test has been added.
=> fix: evaluation of functions with their own nested identifiers

src/__tests__/__snapshots__/preval.test.js.snap, src/babel/evaluate.js, src/babel/module.js
=> fix: get dependencies during evaluation

package.json, src/stylelint/preprocessor.js, src/transform.js
The formatting is a bit messed up due to stylelint's pretty-printing. But all important information is there.
=> fix: don't suppress JS parsing errors in stylelint

package.json, yarn.lock
See comments of https://github.com/callstack/linaria/issues/361
**Summary**
This adds a dependency to `core-js@^2.0.0` which is  implicitly required through the Babel build (because of `"useBuiltIns": "usage"` in `.babelrc`).
/lib/loader.js:
```js
require("core-js/modules/es6.regexp.to-string");
require("core-js/modules/es6.regexp.replace");
```
Now that `core-js@3` is out, upgrading a project can break the linaria webpack loader because `core-js`'s import paths changed. Adding the dependency to linaria should take care of keeping a copy of `core-js@2` around.
**Test plan**
This can be tested by linking the modified version of linaria into a project that uses `core-js@3`
=> fix: add missing core-js dependency

.circleci/config.yml
we need to remove flow check to push TS migration
=> chore: disable flow check to make CI green

src/loader.js
**Summary**
Currently, linaria is able resolve webpack's `alias`, but `modules` should also be supported: https://webpack.js.org/configuration/resolve#resolvemodules
**Test plan**
In our webpack.config.js, we use `resolve.modules` to be able to import modules from our root source:
```js
module.exports = {
// ...
resolve: {
modules: [path.resolve(__dirname, 'src'), 'node_modules']
},
}
```
***Before***
```js
import { css } from 'linaria'
import { rem } from '../../../utils/css'
export const cxMain = css`
display: flex;
margin: ${rem(12)};
`
```
***After***
```js
import { css } from 'linaria'
import { rem } from 'utils/css'
export const cxMain = css`
display: flex;
margin: ${rem(12)};
`
```
We've been patching linaria for the last ~20 days adding this line of code to `lib/loader.js` but I …
=> feat: Support webpack's resolve.modules

docs/BUNDLERS_INTEGRATION.md
Updated the bundlers integration docs to replace suggestion to use  style-loader or css-hot-loader with mini-css-extract-plugin
mini-css-extract-plugin can now handle this internally and css-hot-loader has been discontinued.
This is a doc change. The example code was pulled from a functioning installation.
=> Changed suggestion for hot style reloading

src/__tests__/__snapshots__/preval.test.js.snap, src/babel/extract.ts
**Summary**
New extractor used a wrong list of dependencies that could cause problems with `babel-plugin-module-resolver`.
**Test plan**
Related test from `preval.test.js` was rollbacked to pre-migration state.
=> fix: use evaluated dependencies instead of extracted

src/__tests__/__snapshots__/shaker.test.ts.snap, src/__tests__/depsGraph.test.ts, src/__tests__/shaker.test.ts, src/babel/evaluate/identifierHandlers.ts
**Summary**
```
const key = 'blue';
const obj = { blue: '#00F' };
const blue = obj[key];
```
In cases like this, shaker threw away `key` declaration.
**Test plan**
=> fix: "[…] is not defined" for MemberExpression

src/__fixtures__/components-library.js, src/__tests__/__snapshots__/preval.test.js.snap, src/__tests__/preval.test.js, src/babel/evaluate/templateProcessor.ts, src/babel/utils/getLinariaComment.ts, src/babel/visitors/TaggedTemplateExpression.ts
I've found a bug in the new extractor.
```
export const T1 = styled.h1`background: #111;`;
export const T2 = styled.h2`background: #222;`;
export const T3 = styled.h3`${T2} { background: #333; }`;
```
Extractor finds referenced `T2` and tries to shake the original file in order to evaluate it. As a result, we get code like this:
```
import { styled } from '../react';
const T2 = styled.h2`background: #222;`;
const wrap = fn => {
try {
return fn();
} catch (e) {
return e;
}
};
module.exports = [wrap(() => T2)];
```
Looks fine, but in the process of evaluation, T2 will get a class name based on a wrong `state.index` ( `${relative(state.file.opts.root, state.file.opts.filename)}:0` instead of `${relative(state.file.opts.root, state.file.opts.filename)}:1`).
I'm currently looking for a …
=> Fix for broken interpolation

docs/BUNDLERS_INTEGRATION.md
**Summary**
Best practice for Webpack assets is to include a hash in the filename. This allows far future expires headers to be used, as the filename changes whenever the contents change.
**Test plan**
👀
=> [docs][webpack] Use hash in CSS filename

.all-contributorsrc, docs/CONFIGURATION.md, src/babel/types.js, src/babel/visitors/TaggedTemplateExpression.js
**Summary**
At GoDaddy we need the ability to generate a set of .css files which have consistent class names. Having the hash in/as the class name will not work for us as we have teams that only use our CSS (they don't have any React components).
This PR would enable GoDaddy to use Linaria as it provides the ability to generate a CSS class name which is consistent to the `displayName`. In using this new option, the end user takes responsibility for any class name collisions.
```
module.exports = {
displayName: true,
classNameSlug: '[title]',
};
```
A file called `header.jsx`:
```
import colors from './colors'
import { css } from 'linaria';
import { modularScale, hiDPI } from 'polished';
import fonts from './fonts';
// Write your styles in `css` tag
const header = css`
color: …
```
=> Add classNameSlug option

docs/BASICS.md, src/__tests__/__snapshots__/styled.test.js.snap, src/__tests__/styled.test.js, src/react/styled.ts
Hello.
We like linaria approach and we would like to use BEM approach with it. We have a simple use case:
```css
.component {
...
}
.component--primary {
...
}
```
We cannot use `className` prop for this purpose because it can contain `className`, which is passed to component on render:
```js
function CoolComponent({ className, style, variant, ...rest }) {
const classes = classnames(
className,
{[`${className}--primary`]: (variant === 'primary')} // will not work, because className === "some-class <component class>"
)
return (
<div className={classes} style={style}>
{...}
</div>
);
}
const StyledCoolComponent = styled(CoolComponent)`
background-color: tomato;
&--primary {
background-color: yellow;
}
`;
// render
<StyledCoolComponent className="some-class" />
```
Also component can refer …
=> docs: add information how to extract className for components

README.md
Vscode extension moved. See: https://github.com/stylelint/stylelint/commit/0c7114a514af6f3ba5cb9dc7af0664f8729b594c
=> docs: Update link to vscode sytlelint

.babelrc, package.json, src/__tests__/__snapshots__/babel.test.js.snap, src/__tests__/__snapshots__/preval.test.js.snap, yarn.lock
**Summary**
linaria has a core dependency of corejs v2, however corejs v2 is deprecated and it is not supported anymore. To keep up with the other working environment which are up to date, corejs version has been updated to v3 with this plan.
Here is the issue link: https://github.com/callstack/linaria/issues/420
**Test plan**
The PR successfully passes all the tests within repo and it is locally tested to check it's sanity.
=> feat: upgraded corejs to v3

package.json, src/react/styled.ts
**Summary**
* fixed #520
* fix the issue currently tsc will notice `Module '"/.../node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag` when this option is not turned on
**Test plan**
1. I made these changes
1. I ran `yarn pack` and use `tar --list -f linaria-v1.4.0-beta.1.tgz` to check `/react.d.ts` is already packed
1. I use `yarn link` link this repo to an existed repo to check the second commit is ok
=> Fix some minor ts type related issue

.circleci/config.yml
**Summary**
This fixes #206 
Currently, The CI runs on Node v10. 
The current Node LTS versions are v10 and v12, so we should test on the versions.
https://nodejs.org/en/about/releases/
This PR changes the Node version of lint tasks to v12 (current LTS version) and run unit tests on v10 and v12.
**Test plan**
=> chore(ci): run unit tests on Node v10 and v12

docs/DYNAMIC_STYLES.md
**Summary**
This provides an example of using data attributes as a way of creating semi-dynamic styles based off arbitrary props.
**Test plan**
This is a documentation change only.
=> docs: add example of data attributes for semi-dynamic styling

react.d.ts
**Summary**
When you add interface with custom props to the styled component generic you will lose autocomplete for HTML element attributes. So I combine default HTML elements attributes with user-defined props.
**Test plan**
```typescript
styled.input<{ error : boolean }>
```
before:
after:
=> Combine default HTML elements attributes with user-defined props. (TypeScript, React)

src/babel/utils/throwIfInvalid.js
This Pull Request makes `throwIfInvalid()` pass for `String` and `Number` objects.
Before the change, the following are invalid.
```js
const style = css`
width: ${new String('100%')};
opacity: ${new Number(0.75)};
`;
// throw compilation error `The expression evaluated to 'xxx', which is
// probably a mistake. If you want it to be inserted into CSS, explicitly
// cast or transform the value to a string, e.g. - 'String(mq.XS)'.`
```
After the change, they are valid and the resulting CSS is:
```css
.H0A0S0H0C0L0A0S0S0N0A0M0E {
width: 100%;
opacity: 0.75;
}
```
`String` and `Number` objects are the `Object` equivalence of `string` and `number` primitives. Primitive objects are created using `new String('Hello')` and `new Number(123)`, but primitives are created using `'Hello'` and `123`. …
=> fix: support String and Number object

src/__tests__/module.test.js, src/babel/module.js
Hi! Thank you for the great package.
**Summary**
linaria fails to process imported modules under certain conditions.
The problem is actually with Node, not linaria, see this issue: https://github.com/nodejs/help/issues/2094
**Conditions**
1. The module in question must be executed in strict mode.
2. The module must export a function.
3. The function must be assigned to an `exports` variable.
This may seem like a rare scenario, but I guess there are quite a few modules on NPM that use `exports` this way.
**Solution**
Wrap the module with an additional function wrapper, like so:
```js
(function (exports) {
// code
})(exports);
```
I decided to go just with `exports` because:
- it solves the problem
- changes are minimal
- other variables (`module`, etc) are not affected
**Test plan**
- …
=> linaria fails to process imported modules under certain conditions (Node is to blame)

src/__tests__/__snapshots__/babel.test.ts.snap, src/__tests__/babel.test.ts, src/__tests__/evaluators/__snapshots__/preeval.test.ts.snap, src/__tests__/evaluators/preeval.test.ts, src/babel/evaluators/preeval.ts, src/babel/evaluators/templateProcessor.ts, src/babel/extract.ts, src/babel/visitors/ImportDeclaration.ts, src/babel/visitors/TaggedTemplateExpression.ts
**Summary**
This allows the `styled` import to be locally renamed.
The ImportDeclaration is traversed to check if the imported and local names differ. If so, we store the local name in state and use it in place of the previously hard-coded `'styled'`.
I am not sure if `state.file.metadata` is an appropriate place for this — please feel free to change that.
=> fix: allow styled import to be locally renamed

docs/CONFIGURATION.md, src/__tests__/__snapshots__/babel.test.ts.snap, src/__tests__/babel.test.ts, src/babel/types.ts, src/babel/visitors/TaggedTemplateExpression.ts
**Summary**
Closes https://github.com/callstack/linaria/issues/541
**Test plan**
Added some snapshots to the babel tests. There were no pre-existing tests for the config options — these could do with more robust tests.
=> Allow a function to be passed for classNameSlug option

package.json, src/__tests__/__snapshots__/preval.test.ts.snap, src/__tests__/evaluators/__snapshots__/extractor.test.ts.snap, src/__tests__/evaluators/__snapshots__/shaker.test.ts.snap, src/babel/evaluators/extractor/index.ts, src/babel/evaluators/shaker/index.ts, yarn.lock
Evaluators tried to use default Babel config which is could be configured for using ES-modules that can cause injecting the wrong versions of babel-helpers during evaluation stages. (#517)
This PR explicitly adds `@babel/plugin-transform-runtime` to pre-evaluation transforms.
=> fix(evaluator): forces to use cjs for plugin-transform-runtime

src/babel/module.ts, src/babel/utils/loadOptions.ts
This PR fixes a conflict between `ignore` options (#575).
=> fix(module): fixes a conflict between old ignore option and the new one

docs/2.0_MIGRATION_GUIDE.md
I wanted to inform users on current status of the project since for almost a year there were `1.4.0-beta` releases without a stable version and now we are starting `2.0.0` which might be confusing. 
Updated Readme, added Migration guide.
n/a
=> docs: start 2.0 migration guide

.github/labels.json
label `cat: typings` was matching too often
restricted rules for typings label
=> chore: autolabeling - make typescript matching more restricted

src/__tests__/__snapshots__/babel.test.ts.snap, src/__tests__/__snapshots__/preval.test.ts.snap, src/__tests__/babel.test.ts, src/babel/extract.ts, src/babel/utils/throwIfInvalid.ts
It closes #581 and closes #559 
The evaluation may fail in two ways
- it is not possible to resolve the value because it's dependencies are not available in a static context
- some part of code before actual dependencies was invalid and crashes the vm
I added more information to the first error
I added a stack trace to the second type of error. However, it is not ideal, because line numbers will not match in most cases. I don't know how to improve it, adding some source maps might be complicated. I assume it might not be worth fixing that because those errors will be very rare with the new shaker evaluator. Currently, the error in web back is more verbose thanks to that:
before it skipped the original stack trace
Green CI
=> feat: more verbose report of evaluation error

src/server/__tests__/__snapshots__/collect.test.ts.snap, src/server/__tests__/collect.test.ts, src/server/collect.ts
It fixes #527 
And additionally, I fixed a bug with redundant at rules in critical.
rule
```
@media screen {
body {
font-size: 10px;
}
h1 {
font-size: 20px;
}
.class {
font-size: 15px;
}
}
```
was added 3 times, each time for each child-rule. Amount of repeated adding was equal to amount of child rules.
I added additional processing for top-level @font-face rules.
I added saving processed atrules to set, to avoid re-adding them
I covered changes with additional tests
We need to merge it also to `1.4.x` branch
green CI
=> fix(server): add @font-face to critical, remove redundant atrules.

src/__tests__/__snapshots__/babel.test.ts.snap, src/__tests__/babel.test.ts, src/babel/evaluators/templateProcessor.ts
This will handle blank string values. Sometime after version 1.3.3 the library started throwing an error about being unable to compile blank string values. Now it will just skip the value instead of throwing an error.
We have some mixins which will return a blank string if no conditions are met. Our expectation is that a blank string will cause the CSS property to be ignored (not included) by the compiler.
This PR will cause Linaria to skip blank string values, aka '', instead of throwing an error that linaria does not know how to compile the value.
`yarn test`
=> fix: handle blank string values

src/__fixtures__/components-library.js, src/__tests__/__snapshots__/preval.test.ts.snap, src/__tests__/evaluators/__snapshots__/extractor.test.ts.snap, src/__tests__/preval.test.ts, src/babel/evaluators/extractor/RequirementsResolver.ts, src/babel/evaluators/extractor/index.ts, src/babel/extract.ts, src/babel/types.ts, src/babel/visitors/CollectDependencies.ts
Patch to PR with statements hoisting that fixes two issues:
- sometimes it happened that statements were in different orders which result in the import was defined below its usage.
- during hoisting, if an expression was an identifier, it was replaced with a new identifier that refers to a hoisted value. New identifiers didn't have `start`, `end`, `loc` which result in an error in `templateProcessor`.
I ported sorting statements from `1.3.x`
I make Linaria use a clone of the original statement during evaluation.
Additionally, I added tests for the usage of `styled` in not top-level scope similarly to `css`
New tests added
=> patch: issue 597

src/transform.ts
When Linaria is used in monorepo, one of the possible setups assumes having one `babel.config.js` in the repo root. In order to make it work, we have to set `rootMode: upward`
```js
{
test: /\.jsx?$/,
exclude: [/node_modules/],
use: [
{
loader: 'babel-loader',
options: {
rootMode: 'upward',
}
},
{
loader: 'linaria/loader',
options: {
sourceMap: process.env.NODE_ENV !== 'production',
babelOptions: {
rootMode: 'upward',
}
},
},
],
},
```
In webpack.
During the evaluation, we use file path to generate a `slug` that is used to generate `className`.
https://github.com/callstack/linaria/blob/fb65ee41bf569baa78affbdb2fb74d6bc8784b60/src/babel/visitors/TaggedTemplateExpression.ts#L167-L175
It happens that **different** slug is generated in basic `evaluation` comparing to `pre-evaluation` for …
=> fix: pass babelOptions to initial transform

.circleci/config.yml, src/StyledMeta.ts, src/babel/evaluators/templateProcessor.ts, src/babel/types.ts, src/core/css.ts, src/react/styled.ts, types/styled.ts
This PR fixes issues #622 and #536
The new case was added to dtslint tests and `test:dts` was added to CI for avoiding future regressions.
=> fix: typings for additional props (#622)

src/CSSProperties.ts, src/core/css.ts, src/index.ts, src/react/index.ts, src/react/styled.ts
PR returns missed export of `CSSProperties` (issue https://github.com/callstack/linaria/issues/641)
=> fix(typings): export CSSProperties (closes #641)

package.json, yarn.lock
Add support for `<img />` and `<iframe />` `loading` prop as well as few other props (https://github.com/emotion-js/emotion/blob/master/packages/is-prop-valid/CHANGELOG.md).
This PR updates [@emotion/is-prop-valid](https://github.com/emotion-js/emotion/blob/master/packages/is-prop-valid/) to latest (0.8.8) version.
Not sure if this change can be considered breaking, `loading` seems like a pretty common name for a prop, but I guess it can be released as part of 2.0.
Current workaround:
```javascript
const Foo = styled((props) => <img {...props} />)`
// styles
`
<Foo loading="lazy" />
```
=> Bump @emotion/is-prop-valid

src/rollup.ts
Resolves #638.
1. Clone the demo app: https://github.com/pnfcre/nollup-linaria-demo.
2. Run `yarn start` and open the demo app at http://localhost:9001.
3. Example: Change the `font-size` of the `Title` component in `src/app.tsx` to `2rem`.
4. Notice how changes are *not* reflected in the demo app.
5. Exit the development server and run `yarn run patch`, and repeat step 2 and 3.
6. Notice how changes *are* reflected in the demo app.
Thanks!
=> fix: create rollup slug from cssText

src/babel/process.ts
It fixes #666
It looks logical to pass all env variables and not only NODE_ENV. I don't know why we had such a limitation.
=> fix(evaluators): respect environment variables during evaluation

src/react/styled.ts, types/styled.ts
Fix for #622 introduces regression in `styled`:
```
const Header = styled.h1``;
const Block = styled(/* some custom component  */)`
${Header} {
/* styled */
}
`; // type of Block here is inferred from Header and not from the original component
```
The new case for dtslint was added.
=> fix(typings): styled mistakenly infers type from interpolated component

src/__tests__/__snapshots__/babel.test.ts.snap, src/__tests__/babel.test.ts, src/babel/utils/toValidCSSIdentifier.ts
In some cases, Linaria may generate class names that start with a digit, but according to specification, CSS identifier can start only with a letter, hyphen or underscore. (issue #683)
This PR modifies `toValidCSSIdentifier` in order to catch the first digit in identifier and replace it with an underscore.
The new test was added.
=> fix: css identifier cannot start with a digit

README.md
The editor plugins section in README lack a popular editor, that is Sublime Text which happen to be my main code editor. I have tried all these plugins and can confirm they support Styled Component as well as Linaria.
Add Sublime Text plugins README that support Linaria. 
No test plan since this is a documentation PR.
=> docs: add Sublime Text editor plugins

packages/webpack-loader/babel.config.js, packages/webpack-loader/package.json, packages/webpack-loader/src/index.ts, packages/webpack-loader/tsconfig.json, packages/webpack5-loader/babel.config.js, packages/webpack5-loader/package.json, packages/webpack5-loader/src/index.ts, packages/webpack5-loader/tsconfig.json, yarn.lock
This PR introduces basic support of Webpack 5. It also includes missed package `@linaria/webpack-loaded` which supports both Webpack v4 and v5 but installs more dependencies than specific v4/v5 versions.
=> feat: loader for webpack 5 and universal webpack loader

packages/shaker/package.json
Remove an unsed production dep.
Like in other packages, dedent is actually a dev dep.
`@linaria/babel`: https://github.com/callstack/linaria/blob/a4258f9ad59cf909825a71dfd2b7473a9b5d61cf/packages/babel/package.json#L41-L44
`@linaria/server`: https://github.com/callstack/linaria/blob/a4258f9ad59cf909825a71dfd2b7473a9b5d61cf/packages/server/package.json#L38-L40
Grep output:
```console
$ grep -r dedent packages/shaker/
packages/shaker/package.json:    "@types/dedent": "^0.7.0",
packages/shaker/package.json:    "dedent": "^0.7.0"
packages/shaker/__tests__/shaker.test.ts:import dedent from 'dedent';
packages/shaker/__tests__/shaker.test.ts:        dedent`
packages/shaker/__tests__/shaker.test.ts:        dedent`
packages/shaker/__tests__/shaker.test.ts:        dedent`
```
Seems to be used only …
=> fix: dedent is a devDep of @linaria/shaker, not a prod dep

packages/babel/__fixtures__/ts-data.ts, packages/babel/__tests__/__snapshots__/babel.test.ts.snap, packages/babel/__tests__/babel.test.ts, packages/babel/src/visitors/GenerateClassNames.ts
Support for syntax like that:
```typescript
import { css } from '@linaria/core';
import { TestEnum } from './ts-data.ts';
export const object = {
[TestEnum.FirstValue]: css``,
[TestEnum.SecondValue]: css``,
}
```
For now, Linaria throws an error if meets a dynamic key. After this PR, Linaria will use normalized source code between `[]` as a display name for the generated class.
New test was added.
=> fix(babel): support for dynamic keys in objects with css as values

packages/rollup/src/index.ts
Rollup tries to parse generated css-files and fails if one of them contains `css` or `styled` strings.
All generated files should be ignored.
=> fix(rollup): problem with 'css' string in generated files (#712)

packages/core/package.json, packages/react/package.json
Initially, it was introduced by @wereHamster in #632, but we weren't sure that it was safe at that moment. Now we have different packages which can be safely marked as side effects free.
=> fix: mark core and react packages as side effects free

packages/babel/__tests__/__snapshots__/babel.test.ts.snap, packages/babel/__tests__/babel.test.ts, packages/babel/src/utils/toCSS.ts
Details can be found in #710 
It can be a breaking change for someone who already uses object interpolation with custom properties.
One of the existed tests was modified.
=> fix(babel): custom properties should not be hyphenated (#710) BREAKING CHANGE

babel.config.js
Looking at my logs in Sentry I found out many users are getting `SyntaxError` originating from Linaria's source code.  
Here is just one example: `SyntaxError: Unexpected token =>  at ? (./node_modules/linaria/lib/react/styled.js:26:1)`
That's because in some older browsers arrow functions are not supported: https://caniuse.com/arrow-functions  
I assume Linaria is possibly compatible with **all browsers with CSS Variables support**: https://caniuse.com/css-variables
By taking this requirement into `targets`, we make sure Linaria builds into a JS library that works for all supported browsers.  
Babel will automatically find out all the necessary `transform` plugins, eg: `transform-arrow-functions { "firefox":"41", "ios":"9.3", "safari":"9.1", "samsung":"4" }` (from babel debug output). …
=> Refine preset-env targets to support more browsers

packages/babel/src/utils/loadOptions.ts
Fixes #727 
Changes test regex in loadOptions to match `node_modules` path on Win machines, not only nix.
1. create sample project with react, linaria and webpack
2. make dummy react component wrapped into react's `memo`
3. wrap abovementioned react component into linaria's `styled`
4. run build in different envs (e.g. linux, macos, windows)
5. build should finish with success
=> fix: loadOptions test regex

docs/2.0_MIGRATION_GUIDE.md, docs/HOW_IT_WORKS.md
Links in some doc files were pointing to wrong location with relative path.
Tweaked the relative path to correctly point to the doc file
=> docs: fixing links to other doc files

packages/babel/src/index.ts, packages/babel/src/transform.ts
Hi all! 👋  Thanks in advance for reviewing my PR! 👀 
My company uses the [Metro module bundler](https://facebook.github.io/metro/) for building our JS bundles. As part of this, we specify our **own [custom babel transformer](https://facebook.github.io/metro/docs/configuration#babeltransformerpath)** for mapping TypeScript source files into their transformed JS equivalent. Our custom transformer calls babel's `transformFromAstSync()` under the hood to do this.
One of the things we'd like to do in our transformer is extract the Linaria CSS from the source file being transformed and, therefore, because we've already created the AST all we need is the **post processing CSS extraction logic**.
Moved the logic for extracting CSS from the AST into the `extractCssFromAst()` function and export it …
=> feat(babel): expose CSS extraction from AST logic

packages/babel/src/utils/hasImport.ts
https://github.com/callstack/linaria/issues/739
When import `css` from some module like './utils',  webpack will throw an error "Cannot find module 'linaria'"
```js
import { css } from './utils';
...
```
Because the package 'linaria' is deprecated, At [here](https://github.com/callstack/linaria/blob/master/packages/babel/src/utils/hasImport.ts#L47) try the resolve this. And then require.resolve will throw an exception.
use this case https://codesandbox.io/s/linaria-demo-forked-rbivr?file=/src/index.js
=> fix: Import custom identifier called css with error "Cannot find module 'linaria'" #739

docs/MIGRATION_GUIDE.md
@Anber said that the [main blocker to v3 release is documentation](https://github.com/callstack/linaria/pull/737#issuecomment-788650797).
Add some docs on how to migrate to v3.
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/callstack/linaria/742)
=> docs: guide to upgrading to v3

packages/core/__tests__/cx.test.ts, packages/core/src/css.ts, packages/core/src/cx.ts
Fix for https://github.com/callstack/linaria/issues/746
Spread operators aren't really necessary in `core`, so I've separated type-definition and implementation and made the implementation fully es5 compatible.
A new tiny test was added.
=> fix(core): remove unnecessary spread operators from css and cx (#746)

babel.config.js, packages/react/src/styled.ts
Linaria can partially work even in IE (except prop-based interpolation), but we don't transpile `core` and `styled` to es3, so people with old browsers get completely broken page. This PR fixes that issue. https://github.com/callstack/linaria/issues/746
- dropped `not ie 11` from the targets;
- replaced unsupported functions;
- overridden polyfills config for core-js.
=> fix(core,react): make IE 11 compatible (fixes #746)

package.json, packages/babel/package.json, packages/cli/package.json, packages/core/package.json, packages/extractor/package.json, packages/linaria/package.json, packages/logger/package.json, packages/preeval/package.json, packages/react/package.json, packages/rollup/package.json, packages/server/package.json, packages/shaker/package.json, packages/stylelint/package.json, packages/webpack-loader/package.json, packages/webpack4-loader/package.json, packages/webpack5-loader/package.json, yarn.lock
Allow developing on Windows
Add [cross-env](https://npmjs.org/cross-env) to execute scripts with environment variables.
No test needed.
The pre-commit hook failed:
```
FAIL __tests__/detect-core-js.test.js
● Ensures that package do not include core-js dependency after build
expect(received).toContain(expected) // indexOf
Expected substring: "Based on your code and targets, core-js polyfills were not added"
Received string:    "Successfully compiled 5 files with Babel (701ms).
"
28 |   // run `DEBUG_CORE_JS=true yarn build:lib` to debug issues with introduced core-js dependency
29 |   expect(result).not.toContain('Added following core-js polyfill');
> 30 |   expect(result).toContain(
|                  ^
31 |     'Based on your code and targets, core-js polyfills were not added'
32 |   ); …
```
=> chore: allow install scripts to run on Windows

packages/cli/bin/linaria.js
This PR fixes a regression in @linaria/cli
See #753
=> fix(cli): cannot find module '../lib/cli' (#753)

packages/core/package.json, packages/react/package.json
In vs code ide, if I auto import the `css` method, I will get the code: `import { css } from "@linaria/core/types";`.
It maybe a bug of vs code, but I don't think they will fix it recently. This pr could avoid this issue.
Do as the screenshot above.
=> chore: fix vscode auto import incorrect path

packages/babel/__fixtures__/enums.ts, packages/babel/__tests__/depsGraph.test.ts, packages/babel/__utils__/strategy-tester.ts, packages/babel/src/extract.ts, packages/extractor/__tests__/__snapshots__/extractor.test.ts.snap, packages/shaker/__tests__/__snapshots__/shaker.test.ts.snap, packages/shaker/__tests__/shaker.test.ts, packages/shaker/src/graphBuilder.ts, packages/shaker/src/langs/core.ts
Fix for https://github.com/callstack/linaria/issues/761
Enums are transpilled to functions with side effects, which `shaker` mistakenly drops.
```typescript
enum Color {
black = '#000'
}
```
to
```js
var Color;
(function (Color) {
Color["black"] = "#000";
})(Color || (Color = {}));
```
This PR changes the way how `shaker` evaluates dependencies of statements and expressions.
One test was added, few tests were extended.
=> fix(shaker): typescript enums support (#761)

docs/BUNDLERS_INTEGRATION.md, packages/esbuild/README.md, packages/esbuild/babel.config.js, packages/esbuild/package.json, packages/esbuild/src/index.ts, packages/esbuild/tsconfig.json, yarn.lock
This pull request adds support for esbuild, making bundling code a lot faster.
This integration works similarly to the rollup integration. It returns a function where the user can pass the configuration and it returns the esbuild plugin. The plugin keeps a `cssLookup` map and loads all js, jsx, ts, and tsx files and transforms them using esbuild's transform API to transpile ts and jsx to js. It then passes that result to linaria's babel plugin to transform it, extract the CSS file, and add a new entry in the `cssLookup`. It also appends the CSS file import to the js file and passes it to esbuild's CSS loader.
=> feat: add esbuild integration

packages/rollup/src/index.ts
@linaria/rollup inject the css file with a real file path, but the css flie not exist in file system.
And vite [rewrite the absolute path with a relative path](https://github.com/vitejs/vite/blob/5745a2e8072cb92d647662dc387e7f12b2841cab/packages/vite/src/node/plugins/importAnalysis.ts#L195), so vite server could not find the the css file from file system and @linaria/rollup could not find it from `cssLookup` object.
I add a `@linaria:` prefix to css filename so that rollup and vite see it as a **virtrul** file.
Make it work for vite.
=> fix: @linaria/rollup compliant vite

packages/webpack4-loader/src/index.ts, packages/webpack5-loader/src/index.ts
In case of an error, webpack loaders don't mark some files as a dependency and that causes problems with HMR. (#762)
This PR adds an explicit call of `addDependency` for required files.
=> fix(webpack): hot reload fails after compile error (fixes #762)

README.md, packages/interop/README.md, packages/interop/__tests__/__snapshots__/index.test.js.snap, packages/interop/__tests__/index.test.js, packages/interop/index.js, packages/interop/package.json
Linaria can be used together with traditional CSS-in-JS libraries, but styled components cannot be used as selectors in `styled-components`/`emotion` styles. This PR introduces a plugin that allows such an interoperability
=> feat(interop): interop between Linaria and traditional CSS-in-JS libraries

packages/esbuild/src/index.ts
The previous way of importing esbuild would lead the error:
> node_modules/@linaria/esbuild/lib/index.js:74:29: error: [plugin: linaria] Cannot read property 'transformSync' of undefined
74         } = _esbuild.default.transformSync(rawCode, { ...esbuildOptions,
When using linaria with esbuild as described here: https://github.com/callstack/linaria/blob/master/docs/BUNDLERS_INTEGRATION.md#esbuild one would get a failing build due to the import not working as expected. Error message:
``` > node_modules/@linaria/esbuild/lib/index.js:74:29: error: [plugin: linaria] Cannot read property 'transformSync' of undefined
74 │         } = _esbuild.default.transformSync(rawCode, { ...esbuildOptions,
╵                              ^
at ./node_modules/@linaria/esbuild/lib/index.js:74:30
at callback …
```
=> fix(esbuild): import esbuild correctly

packages/esbuild/src/index.ts
When using esbuild with preact the jsxFactory and jsxFragment parameter are used to use h() rather than React.createElement(). This change ensures that the parameters are passed to the transform function.
This workaround checks if jsxFactory or jsxFragment are part of the original build options and if so copies them to to the transform options.
NOTE 1: Usually esbuild would just pick up on tsconfig.json - this workaround won't work there. The pararmeters must be provided explicitly.
NOTE 2: The plugin should probably be rewritten on a more fundamental
level as it interefers heavily with the esbuild build process.
Setup an esbuild sample project with preact and linaria, then use this build script and check that there is no "React.createElement" in the bundle:
```
const { build } = …
```
=> fix(esbuild): workaround to for esbuild compile options

docs/CONFIGURATION.md, packages/webpack4-loader/src/index.ts, packages/webpack5-loader/src/index.ts
We have some packages that export both ESM and CommonJS modules using [conditional package exports](https://webpack.js.org/guides/package-exports/#conditions) using the `import` and `require` conditions, such as [in this example](https://github.com/rmazzeo-godaddy/linaria-conditionnames-missing/blob/main/simple-dependency/package.json#L12-L21). These work fine in our Webpack 5 apps, however if we try to use these imports in Linaria blocks with the Linaria Webpack loader, it blows up with the error:
```
Package path ./sizes is not exported from package
```
What's missing is that the Linaria webpack loaders do not pass down the appropriate `conditionNames` to the enhanced resolver. This PR adds the `require` condition name by default, and also introduces the ability to customing the loader …
=> fix: webpack resolve options

packages/babel/__tests__/evaluators/__snapshots__/shaker.test.ts.snap, packages/babel/__tests__/evaluators/shaker.test.ts, packages/shaker/src/graphBuilder.ts
Shaker didn't process exports when they were defined with string literals (`exports["foo"] = 42` instead of `exports.foo = 42`).
Just a small fix that will resolve #333 and hopefully #761
One test was extended.
=> fix(shaker): fix undefined imports in some cases (#333, #761)

docs/BUNDLERS_INTEGRATION.md
Replace Rollup by esbuild in esbuild section
=> docs(bundlers): fix esbuild section typo

packages/esbuild/src/index.ts
When attempting to bundle a font before, esbuild would complain:
```
> linaria:App_hash.linaria.css:1:46: error: Could not resolve "./font.ttf" (the plugin "linaria" didn't set a resolve directory)
1 ? @font-face{font-family:"font";src:url("./font.ttf");}...
```
With this fix the `resolveDir` is set to the basedir of the file loading the font (or other external asset) and thus relative paths should work just fine.
Note: When testing this, configure the esbuild build to include the appropriate loader, e.g.:
```
loader: { ".ttf": "dataurl" },
```
=> fix(esbuild): add missing resolveDir to support webfont bundling

packages/babel/__tests__/evaluators/__snapshots__/preeval.test.ts.snap, packages/babel/__tests__/evaluators/__snapshots__/shaker.test.ts.snap, packages/babel/__tests__/evaluators/preeval.test.ts, packages/preeval/src/index.ts
See https://github.com/callstack/linaria/issues/800
In some cases, Babel generates code that depends on hoisted variables. Since `shaker` uses simplified tree traversing, it doesn't properly process those cases and isn't able to evaluate the dependencies of a shaking file.
The best solution here would be migration to `@babel/traverse`. However, it will take a while.
So that, this PR implements the worst solution :) I've added a dirty hack to `preeval`, that checks that generated code has those "wrong" variables and hoists them.
One test was added, one test was fixed.
=> fix(shaker): named exports are removed (#800)

packages/babel/__tests__/evaluators/__snapshots__/shaker.test.ts.snap, packages/babel/__tests__/evaluators/shaker.test.ts, packages/shaker/package.json, packages/shaker/src/DepsGraph.ts, packages/shaker/src/langs/core.ts, packages/shaker/src/scope.ts, yarn.lock
See #804 
This PR adds a workaround that processes `exports.somethings` expressions as regular variables in a global scope.
One new test was added.
=> fix(shaker): keep exports if there are dependent code (fixes #804)

packages/shaker/__fixtures__/bar.js, packages/shaker/__fixtures__/foo.js, packages/shaker/__fixtures__/reexports.js, packages/shaker/__tests__/__snapshots__/shaker.test.ts.snap, packages/shaker/__tests__/shaker.test.ts, packages/shaker/src/DepsGraph.ts, packages/shaker/src/graphBuilder.ts, packages/shaker/src/langs/core.ts, packages/shaker/src/shaker.ts
See #808 
In case of re-export, files don't explicitly contain identifiers that should be kept and `shaker` wasn't able to link exported variables with imported files. This PR fixes that.
A new test was added.
=> fix(shaker): support for "export * from …" (fixes #808)

packages/core/__tests__/detect-core-js.test.js, packages/react/__tests__/detect-core-js.test.js, packages/react/src/styled.ts
`@linaria/styled` imports a few unnecessary polyfills.
It appeared, that our `detect-core-js` tests were broken and didn't detect a leak of core-js polyfills. The leak itself was caused by wildcard import from `react`.
Boths `detect-core-js` were fixed.
=> fix(styled): remove unnecessary core-js polyfills  (fixes #799)

packages/shaker/__tests__/__snapshots__/shaker.test.ts.snap, packages/shaker/__tests__/shaker.test.ts, packages/shaker/src/DepsGraph.ts, packages/shaker/src/langs/core.ts, packages/shaker/src/shaker.ts
Shaker didn't properly work with constructions like:
```
const module = require('./module');
const value = module["value"]; // `value` here wasn't recognized as an imported value
```
This PR adds support of string literals in the imported values usages detector.
One test was modified.
=> fix(shaker): support string literals for addressing values in imported NS

packages/babel/src/utils/loadOptions.ts
I want to use Linaria without evaluating the interpolated values. So I don't need to install `@linaria/shaker` but `@linaria/babel-preset` requires the package if no evaluator rules are active.
The default evaluator rules will be skipped when any rules option is set. It makes `@linaria/shaker` optional.
Related #813.
A rollup example. This should work without `@linaria/shaker` installed.
```js
import linaria from '@linaria/rollup';
export default {
plugins: [
linaria({
rules: [],
}),
],
};
```
=> feat: make @linaria/shaker optional

packages/shaker/src/DepsGraph.ts
Fixes https://github.com/callstack/linaria/issues/797
I'm pretty surprised that this has any impact, I don't have a good rationale for why but it appears to be dramatically faster to update the array in place.
Using the demo repo linked in the above issue without this change:
```
$ webpack
asset app.js 961 KiB [compared for emit] (name: app) 1 related asset
asset styles.css 8.35 KiB [compared for emit] (name: app) 1 related asset
Entrypoint app 969 KiB (1.11 MiB) = styles.css 8.35 KiB app.js 961 KiB 2 auxiliary assets
orphan modules 390 bytes [orphan] 3 modules
runtime modules 670 bytes 3 modules
modules by path ./node_modules/ 947 KiB
modules by path ./node_modules/scheduler/ 32.4 KiB 4 modules
modules by path ./node_modules/react/ 59.4 KiB 2 modules
modules by path …
```
=> fix: Faster method of building dependencies array

packages/babel/__tests__/__snapshots__/babel.test.ts.snap, packages/babel/__tests__/babel.test.ts, packages/babel/src/types.ts, packages/babel/src/utils/isSlugVar.ts, packages/babel/src/visitors/GenerateClassNames.ts
Fixes #650
Fixes #571
If you want to know where a particular class is coming from, you need more than a hash or even the original title of the class. How many `.inner` or `.title` classes have you seen in a large codebase, right?
This PR adds four new vars to `classNameSlug` resolution. It also adds the original two `hash` and `title` to the object, with the idea that a future breaking change might sandwich the function parameters down to just this one.
While just `file` would have been sufficient for function style, I added `dir, name, ext` for ease of use with string-style. Here's what you would expect in each:
```ts
{
hash: 'qdegrke',
title: 'displayName',
file: 'this/is/your/module/Component/SubComp.tsx',
name: 'SubComp',
ext: 'tsx',
dir: 'Component',
}
```
Added tests.
=> feat: Add {file, name, dir, ext} to `classNameSlug` resolution

packages/babel/__fixtures__/reexports/constants.ts, packages/babel/__fixtures__/reexports/foo.ts, packages/babel/__fixtures__/reexports/index.ts, packages/babel/src/module.ts, packages/shaker/__tests__/__snapshots__/shaker.test.ts.snap, packages/shaker/__tests__/shaker.test.ts, packages/shaker/src/shaker.ts
Fixes #816
Shaker correctly detected wildcard imports but mistakenly marked everything in the imported file as unnecessary.
A new test was added.
=> fix(shaker): improve dependency resolution for wildcard exports

packages/react/src/styled.ts
TypeScript 4.4 introduced [new `--exactOptionalPropertyTypes` flag](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#exact-optional-property-types---exactoptionalpropertytypes). With this flag enabled typescript compiler strictly distinguish between `?` and `undefined` type. Currently [`@types/react:17.0`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c134157852d95b32a5feeb675e13489b76fbeda0/types/react/index.d.ts#L1831-L1842) package has `className?: string | undefined` and `style?: CSSProperties | undefined` specified for html attributes, but linaria types are only marked as `?` but `undefined`. This patch fixes this incompatibility
=> Fixes for `--exactOptionalPropertyTypes` TS flag

packages/rollup/src/index.ts
fix #818 
With the `preserveModules`, rollup will not add the `.js` file extension: https://github.com/rollup/rollup/blob/ebb3ff69c334b89cc58e3ed5488860f5a4597604/src/Chunk.ts#L440
Instead of use a `virtual module`, here use the original way.
If it run as vite serve, the id is a url like `/src/componets/Hello_xxx.css`.
So add it as a key of `cssLookup`.
=> fix: rollup preserveModules no js extension

packages/core/src/css.ts, packages/core/src/cx.ts, packages/core/src/index.ts
Strictly typed `css` significantly simplified the creation of `@linaria/eslint` plugin which can check that there are no constant class names in user code.
```
const fooString = "foo";
const fooClass = css``;
<div className="foo" /> 
<div className={fooString} /> 
<div className={fooClass} /> 
<div className={cx(condition && fooClass)} /> 
<div className={cx(condition && "foo")} /> 
<div className={cx(condition && fooString)} /> 
```
`css` returns `LinariaClassName` instead of `string`.
`cx` returns `LinariaClassName` if every argument is `LinariaClassName`, otherwise it return `string`.
=> fix(core): return type alias instead of string from `css` and `cx`

packages/babel/__tests__/evaluators/__snapshots__/shaker.test.ts.snap, packages/babel/__tests__/evaluators/shaker.test.ts, packages/shaker/src/DepsGraph.ts, packages/shaker/src/graphBuilder.ts, packages/shaker/src/langs/core.ts, packages/shaker/src/scope.ts
Precompiled code in node_modules can contain some tricky constructions which are not supported by shaker. (#820)
This PR adds basic support for TS-exports and fixes some related issues.
=> fix(shaker): partial support for ts compiled code (fixes #820)

src/react/styled.ts
Suppose I have:
```tsx
type GridProps =
| { container?: false }
| { container: true; spacing: number }
declare const Grid: React.FC<GridProps & { className?: string }>
// ❌ should not compile
const testGrid = <Grid container={false} spacing={8} />
/**
Type '{ container: false; spacing: number; }' is not assignable to type 'IntrinsicAttributes & PropsWithChildren<GridProps & { className?: string | undefined; }>'.
Property 'spacing' does not exist on type 'IntrinsicAttributes & { container?: false | undefined; } & { className?: string | undefined; } & { children?: ReactNode; }'.
*/
// ✅ compiles
const testGrid = <Grid container={true} spacing={8} />
```
The idea is to have an extra guard where you can only pass `spacing` as a prop when `container` is `true`. But unfortunately the current …
=> fix(react): unions in prop types are not resolved

docs/BUNDLERS_INTEGRATION.md
After upgrading Webpack, I was getting this error:
```
ValidationError: Invalid options object. Mini CSS Extract Plugin Loader has been initialized using an options object that does not match the API schema.
- options has an unknown property 'hmr'. These properties are valid:
object { publicPath?, emit?, esModule?, layer? }
```
Seems like this option isn't supported any more.
=> Remove "hmr" option from Webpack docs

packages/babel/src/extract.ts, packages/shaker/src/GraphBuilderState.ts, packages/shaker/src/langs/core.ts
See #861
If an exported identifier was used as an object's index in a left part of an assignment operator, that identifier was mistakenly interpreted as a declaration instead of reference.
=> fix(shaker): exports/object issue with TS (fixes #861)

docs/BUNDLERS_INTEGRATION.md
I'm not sure, but I think there was a full stop missing which initially confused me.
=> Fix minor typo in docs

packages/cli/src/linaria.ts
Running `linaria` CLI with a glob wildcard produced an error if the directory contains nested folders.
```
/build
/components
/SomeComponent.js
/index.js
/src
/components
/SomeComponent.tsx
/index.ts
```
```sh
yarn linaria -o build -r src -i build ./src/**/*
```
Simply check if the file is a `directory` before we run any transformations.
It works with nested directories - scenario presented above. There is no unit testing set up for `@linaria/cli` so I skipped adding test cases for this.
=> fix: cli trying to transform directories

packages/logger/package.json, packages/logger/src/index.ts, packages/webpack4-loader/src/index.ts, packages/webpack5-loader/src/index.ts, yarn.lock
Fixes #855 and regression from #830
In #830 we decided to use the whole Webpack configuration in Linaria's resolver. It appeared, that it wasn't the wisest decision because it introduced a lot of breaking changes. This PR introduces a better merge for Webpack config with default Linaria's config and adds a fallback if Webpack configuration breaks the resolver by using some async plugins.
=> fix(webpack): better merge for configs and fallback for async plugins

packages/stylelint/src/index.ts, packages/stylelint/src/preprocessor.ts
Existed implementation of the stylelint processor generates empty lines that cause false-positive `no-empty-first-line` warnings.
This PR reimplements warnings positions adjustment in order to generate more clean CSS without redundant empty lines.
=> fix(stylelint): fix indentation errors (fixes #693)

docs/BUNDLERS_INTEGRATION.md, packages/webpack4-loader/package.json, packages/webpack4-loader/src/index.ts, packages/webpack4-loader/src/outputCssLoader.ts, packages/webpack5-loader/package.json, packages/webpack5-loader/src/index.ts, packages/webpack5-loader/src/outputCssLoader.ts, yarn.lock
Current implementations of webpack loaders use file system cache for storing evaluated css-files. It causes a few problems with URLs in CSS, with HMR and even with finding a root of a project (if Linaria is used in monorepo). At the same time, Rollup loader uses in-memory cache that works pretty good.
In #878 @malash suggested using `inline matchResource` in order to fix doubled reloads. It appeared, that with such a tool we can finally get rid of filesystem cache and migrate to in-memory cache, which seems to be much more problemless.
=> fix(webpack): replace file system cache with in-memory cache (fixes #878)

docs/CONFIGURATION.md, packages/babel/__tests__/__snapshots__/babel.test.ts.snap, packages/babel/__tests__/babel.test.ts, packages/babel/src/types.ts, packages/babel/src/utils/getTemplateType.ts, packages/babel/src/utils/hasImport.ts, packages/babel/src/visitors/CollectDependencies.ts, packages/babel/src/visitors/GenerateClassNames.ts, website/src/api/react/index.js
This addresses https://github.com/callstack/linaria/issues/851
The docs should explain the solution here fairly well – let me know if more detail would help.
Basically, adds a custom resolver that can be used in `hasImport` to allow building linaria libs from different folders
I tested this by trying it out in the `website/` folder. It worked there, and I added some snapshot tests too
=> feat(resolver): add custom resolver option to support re-exporting of linaria libs

packages/webpack4-loader/src/index.ts, packages/webpack5-loader/src/index.ts
There's no existing issue for this as far as I know.
Fixes an issue like this:
```
INFO ==>  ModuleBuildError: Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
--
INFO ==>  Thread Loader (Worker 6)
INFO ==>  Cannot read property 'extensions' of undefined
```
There are some contexts in which the `webpackResolveOptions` might be undefined – eg issues like https://github.com/TypeStrong/ts-loader/issues/1206 .
In general the loader handles `this._compilation` not being there, but in practice, breaks because of this line. You can see on line 86 that this is meant to handle the case where `webpackResolveOptions` is undefined, but it was just missed there (if only we could do it in typescript! But I imagine that's more trouble than it's worth for a webpack loader)
You can …
=> fix(webpack): fix usage of webpackResolveOptions conditionally

docs/BUNDLERS_INTEGRATION.md, src/cache.ts, src/loader.ts, src/outputCssLoader.ts
This PR try to fix https://github.com/callstack/linaria/issues/881 . This PR is mainly inspired from https://github.com/callstack/linaria/commit/a281440271cb29d4d2e2b0cb3b2fee26f1e4bc69
This PR add a new option `cacheProvider` for Linaria loader.
- `cacheProvider: undefined | string | ICache` (default: `undefined`):
By default Linaria use a memory cache to store temporary CSS files. But if you are using this loader with [thread-loader](https://www.npmjs.com/package/thread-loader) you should use some consistent cache to prevent [some unexpected issues](https://github.com/callstack/linaria/issues/881). This options support a `ICache` instance or a path to NodeJS module which export a `ICache` instance as `module.exports`
> ```
> interface ICache {
>   get: (key: string) => Promise<string>; …
```
=> fix(webpack): add cacheProvider to support customized cache

docs/BUNDLERS_INTEGRATION.md, packages/webpack4-loader/src/cache.ts, packages/webpack4-loader/src/index.ts, packages/webpack4-loader/src/outputCssLoader.ts, packages/webpack5-loader/src/cache.ts, packages/webpack5-loader/src/index.ts, packages/webpack5-loader/src/outputCssLoader.ts
This PR add the same feature as https://github.com/callstack/linaria/pull/884 for Linaria v3.
See https://github.com/callstack/linaria/pull/884
I tested this PR in https://github.com/malash/linaria-issue-881/commit/ae8ecca1d8adb812c39ede9c897d405549fa5ae4 with `cacheProvider: undefined` and `cacheProvider: require.resolve("./linariaFileCache")` and they work as expected.
@Anber
=> fix(webpack): add cacheProvider for Linaria v3

src/loader.ts
While cherry picking `cacheProvider` to Linaria v3 I found a same bug in https://github.com/callstack/linaria/pull/884
If `cacheProvider` is not set ( `undefined` ), the query param `cacheProvider=${encodeURIComponent(cacheProvider)}`  became a string `'undefined'` and result in a runtime error `Cannot find module 'undefined'`.
I'v test `cacheProvider: undefined` in https://github.com/callstack/linaria/pull/889
=> fix(webpack): fix error when cacheProvider is undefined

package.json, packages/babel/src/extract.ts, packages/babel/src/index.ts, packages/babel/src/types.ts, packages/babel/src/utils/getVisitorKeys.ts, packages/react/__dtslint__/styled.ts, packages/react/src/styled.ts, packages/shaker/src/GraphBuilderState.ts, packages/shaker/src/Visitors.ts, packages/shaker/src/graphBuilder.ts, packages/shaker/src/identifierHandlers.ts, packages/shaker/src/types.ts, packages/stylelint/src/preprocessor.ts, yarn.lock
See #872
Types for `styled` were completely refactored. Now it supports dynamic calls (#872) and shows better errors if a target component has no `className` or `style` properties.
Thank you @Beraliv for helping!
`yarn test:dts`
=> fix(react): refactored types for styled function (fixes #872)

docs/API.md, docs/ATOMIC_CSS.md, docs/CONFIGURATION.md
Add documentation for atomic css.
This documentation depends on https://github.com/callstack/linaria/pull/913, so I'd recommend doing this PR and that PR in the same release.
docs only
N/A
=> feat(atomic): add documentation

docs/ATOMIC_CSS.md, examples/gatsby/custom-config/yarn.lock, packages/atomic/package.json, packages/atomic/src/atomize.ts, packages/atomic/src/css.ts, packages/atomic/src/index.ts, packages/babel/__tests__/__snapshots__/babel.test.ts.snap, packages/babel/__tests__/babel.test.ts, packages/babel/src/evaluators/templateProcessor.ts, packages/babel/tsconfig.json, packages/utils/__tests__/cx.test.ts, packages/utils/src/cx.ts, yarn.lock
Addresses https://github.com/callstack/linaria/issues/912
Should be fairly straightforward after reading the reason why we might want this. I've also updated the documentation to reflect what's going.
Tested with snapshot tests and unit tests. Docs should render the same way
=> feat(atomic): string serialization of atoms

packages/babel/__utils__/strategy-tester.ts, packages/shaker/__fixtures__/assignToExport.js, packages/shaker/__fixtures__/computedKeys.js, packages/shaker/__fixtures__/objectExport.js, packages/shaker/__tests__/__snapshots__/shaker.test.ts.snap, packages/shaker/__tests__/shaker.test.ts, packages/shaker/src/graphBuilder.ts, packages/shaker/src/langs/core.ts
I've tried adopting the shaker method (over extraction) and ran into some edge cases – I've added tests that explain what those edge cases look like.
There are three cases that weren't shaken correctly by the shaker algorithm:
1. Assigning to an export (eg. `var x = module.exports = {...}`)
2. Exporting objects (with computed keys)
3. Exporting objects directly (eg. `module.exports = {...}`) and using this object as a default import elsewhere
This fixes it by changing the shaker algorithm to support these cases.
I think so long as we can get these new tests to pass, I'd be happy to take suggestions on exactly how we can implement the fixes. In particular, the biggest change is to support assigning to an export, for example:
```
var x = module.exports = {...}
```
The issue there is that …
=> fix(shaker): fix some edge cases related to specific export patterns

packages/esbuild/src/index.ts
Resolve #954
Add loader and resolveDir to the return value of build.onLoad. Without them, errors will occur when combined with other external esbuild plugins.
=> fix(esbuild): add add missing loader and resolveDir

packages/stylelint/src/preprocessor.ts
I noticed that our stylelint runs are logging all of our styles. I've
traced this down to this console.log call.
From what I can tell, it looks like this was added by mistake in
https://github.com/callstack/linaria/pull/876
I want to remove noise from my CI logs
See above
N/A
=> Remove console.log from stylelint preprocessor

packages/react/__tests__/__snapshots__/styled.test.js.snap, packages/react/__tests__/styled.test.js, packages/react/src/styled.ts
See #968
This PR fixes props filtration in order to support custom components with UpperCameCase names.
=> fix(react): support UpperCamelCase custom elements #968

packages/babel/__tests__/__snapshots__/babel.test.ts.snap, packages/babel/__tests__/babel.test.ts, packages/babel/src/evaluators/templateProcessor.ts
This fixes a bug I discovered where the same property is getting overriden by other css in the same file. Test case provided for the scenario that's failing
Relatively simple fix – this just uses the CSS text itself as a key in the metadata to ensure that it's unique per rule + declaration, between declarations too.
Fixed with a snapshot test
=> fix(atomic): fix duplication of the same css properties in the same file

packages/babel/__utils__/strategy-tester.ts, packages/babel/src/visitors/CollectDependencies.ts, packages/extractor/__tests__/__snapshots__/extractor.test.ts.snap, packages/shaker/__tests__/__snapshots__/shaker.test.ts.snap
fix: https://github.com/callstack/linaria/issues/957
The issue was caused by the referenced template getting hoisted, converting the path already added to `state.queue` into an identifier referencing the hoisted variable. The code processing the queue expected all paths to be tagged template literals and crashed when trying to access `path.get('quasi').get('expressions')`.
Avoiding hoisting templates when referenced in other templates seem to have solved the problem.
=> fix: error when css calls reference css calls inside components

packages/cli/src/linaria.ts
After https://github.com/callstack/linaria/pull/976 yargs became too strict.
=> fix(cli): doesn't accept list of files

packages/babel/src/evaluators/templateProcessor.ts
See #981 
Do not use `instanceof` in an environment with uncontrolled dependencies.
=> fix(react): styled API prop interpolation #981

.changeset/slow-flowers-rest.md, packages/cli/src/linaria.ts
Previously, CLI could only extract styles from source files, but template tags were kept untouched. 
This PR introduces two new options:
- `--transform` or `-t` that say Linaria, that we want not only extract styles but also replace all template tags with their runtime representations;
- `--modules [name]` or `-m [name]` that specify what type of import will be used: `require(…)` or `import …`.
With this PR and #976, it became possible to use pure tsc compiler and @linaria/cli as postprocessing for building libs.
=> feat(cli): new flag --transform

.changeset/fair-cars-attack.md, .changeset/wicked-mugs-smash.md, packages/atomic/processors/css.js, packages/atomic/processors/styled.js, packages/babel/src/evaluators/templateProcessor.ts, packages/babel/src/utils/getTagProcessor.ts, packages/core/processors/BaseProcessor.js, packages/core/processors/css.js, packages/react/processors/styled.js, packages/testkit/src/utils/getTagProcessor.test.ts
Some environment doesn't support `exports` in `package.json`.
Aliases from roots of packages to lib folders should solve that problem.
=> fix(babel): aliases for processors and fixed resolver

.changeset/twelve-dolphins-sin.md, packages/babel/src/transform.ts, packages/babel/src/types.ts, packages/cli/src/linaria.ts
CLI didn't pass `source-root` to the babel plugin.
=> fix(cli): pass source-root option to babel

packages/esbuild/src/index.ts
=> fix(esbuild): fix broken source maps

packages/babel/src/transform-stages/1-prepare-for-eval.ts, packages/testkit/package.json, packages/testkit/src/__fixtures__/with-babelrc/.babelrc.js, packages/testkit/src/__fixtures__/with-babelrc/index.js, packages/testkit/src/__snapshots__/babel.test.ts.snap, packages/testkit/src/babel.test.ts, pnpm-lock.yaml
Since shaker is evaluated before other plugins, it returns imports without applied `babel-plugin-module-resolver`
=> fix(babel): support for module-resolver

.changeset/empty-papayas-attack.md, packages/shaker/package.json, packages/shaker/src/plugins/__tests__/__snapshots__/shaker-plugin.test.ts.snap, packages/shaker/src/plugins/__tests__/shaker-plugin.test.ts, packages/shaker/src/plugins/shaker-plugin.ts, packages/utils/src/scopeHelpers.ts
=> fix(shaker): shaker doesn't treat exports as variable references (fixes #1008)

.changeset/smart-rivers-exist.md, packages/cli/src/linaria.ts
CLI should not write changes if some files cannot be transformed.
=> fix(cli): write files only when all transformations are finished

.changeset/three-emus-turn.md, packages/babel/src/index.ts, packages/react/src/index.ts, packages/react/src/processors/styled.ts, packages/react/src/styled.ts, packages/shaker/src/index.ts, pnpm-lock.yaml
There are a few problems: the wrong condition in babel-preset, missed caller in Shaker, and the problem with processing already processed `styled`. All of them caused errors in different environments, such as jest and Vite dev-mode.
=> fix(babel, react, shaker): tag in runtime is not supported (fixes #1021)

.changeset/real-terms-brush.md, packages/babel/src/plugins/preeval.ts
The size of evaluated code can be reduced by shaking out all functions that use react hooks.
This PR modifies the preeval stage to detect and delete not only `createElement` calls but all react functions that can be used only inside components.
=> feat(babel): react hooks aren't needed for evaluation

.changeset/wild-eyes-joke.md, packages/babel/src/module.ts
We use module evaluation from Linaria v3 in Griffel. It's expected to have Linaria or Griffel loader after main transformer i.e.:
```js
module.exports = {
module: {
rules: [
{
test: /\.(ts|tsx)$/,
exclude: /node_modules/,
use: [{ loader: "@griffel/webpack-loader" }, { use: "babel-loader" }]
}
]
}
};
```
The problem comes with Next.js and SWC used there. SWC emits helpers in the same way as Babel:
```ts
import _objectSpread from "@swc/helpers/src/_object_spread.mjs";
var a = _objectSpread({}, {
foo: true
});
```
The problem is in an import that points to ESM module while it should point to CJS to successfully evaluate code.
ESM helpers follow this pattern: `node_modules/@swc/helpers/src/_array_with_holes.mjs`
CJS helpers follow this pattern: …
=> fix: update SWC helpers path in module evaluation

.changeset/hot-eagles-impress.md, packages/babel/src/transform.ts, packages/babel/src/utils/getTagProcessor.ts, packages/react/src/processors/styled.ts, packages/tags/src/BaseProcessor.ts, packages/webpack4-loader/src/index.ts, packages/webpack5-loader/src/index.ts, pnpm-lock.yaml
See #1037
This PR introduces a way to skip a tag if it doesn't match the required conditions (e.g. `styled` is used as a call instead of a template tag).
=> fix(babel, react): do not process already transformed literals (fixes #1037)

CONTRIBUTING.md
Noticed that Linaria was migrated to use Pnpm 2 months ago, but the `CONTRIBUTING.md` is outdate
1. change Yarn to Pnpm
2. remove flow in `CONTRIBUTING.md`
Only doc changed, no effect on Linaria function
=> docs(contributing.md): change yarn to pnpm and remove flow

packages/utils/src/scopeHelpers.ts
Should fix #1039 
it's safe to not remove the global var inside `TemplateString`, I replace it with empty string
=> fix(preeval): do not remove global var in string template

docs/CLI.md
CLI has two handy arguments that are missed in the documentation: `-t` and `-m`
=> docs: added -m and -t options for CLI

.changeset/unlucky-goats-tie.md, packages/babel/src/plugins/preeval.ts, packages/babel/src/utils/getTagProcessor.ts, packages/shaker/src/plugins/shaker-plugin.ts, packages/testkit/src/collectExportsAndImports.test.ts, packages/testkit/src/utils/isUnnecessaryReactCall.test.ts, packages/utils/src/collectExportsAndImports.ts, packages/utils/src/index.ts, packages/utils/src/isUnnecessaryReactCall.ts
Depending on the transpiler, `jsx-runtime` can be imported and used in many ways. Some of that ways weren't detected by Linaria, which caused excess code evaluations.
This PR improves `jsx-runtime` detection.
A new set of tests was added.
=> fix(babel): improve jsx-runtime detection

.changeset/chatty-ants-eat.md, packages/babel/src/plugins/babel-transform.ts, packages/babel/src/transform-stages/1-prepare-for-eval.ts, packages/babel/src/transform-stages/3-prepare-for-runtime.ts, packages/babel/src/transform-stages/helpers/cachedParseSync.ts, packages/babel/src/transform.ts, packages/shaker/src/index.ts, packages/utils/src/options/loadBabelOptions.ts, packages/utils/src/options/types.ts
In some cases, the ".key is not a valid Plugin property" error has happened.
The error was caused by using different babel instances (from different node_modules). To avoid that, we can explicitly pass the one babel instance through the whole call stack.
=> fix(bable): avoid using different babel versions

.changeset/stale-bees-collect.md, packages/babel/src/utils/collectTemplateDependencies.ts
Fixes https://github.com/callstack/linaria/issues/1047
This incorrectly failed with an "unsupported error" in cases where the identifier was already hoisted. 
A couple of lines down from here we return early if the `binding.scope.parent` is falsey. So I think it's safe to let this through.
I wasn't able to get the test suite (or bootstrap) to run with pnpm so I haven't included any tests. 
It seems like it would be fairly easy to add a snapshot test along the lines of the following to the test file [here](https://github.com/callstack/linaria/blob/master/packages/testkit/src/babel.test.ts):
```
it('should work with already hoisted vars', async () => {
const { code, metadata } = await transform(
dedent`
function color() {
return 'red\
}
export const square = css\`
color: ${'${color()}'}
\`; …
```
=> Handle already hoisted bindings

.changeset/cold-swans-unite.md, packages/postcss-linaria/__tests__/parse.test.ts, packages/postcss-linaria/src/parse.ts
In vscode, @linaria/postcss-linaria would throw noisey errors due to babel not being able to parse the code the developer is writing as they are writing it.  
The below is a random test file being spammed with toast errors (bottom right) because babel cannot parse this file while I'm typing.
This adds a try/catch to essentially only lint files when the file can be parsed by babel, likely also the time the developer is done typing.
Added spec and tested locally
=> Only lint when file can be parsed by babel (reduces noisey errors as developer types)

.changeset/cuddly-laws-drum.md, .changeset/poor-socks-check.md, packages/babel/src/index.ts, packages/shaker/src/plugins/__tests__/__snapshots__/shaker-plugin.test.ts.snap, packages/shaker/src/plugins/__tests__/shaker-plugin.test.ts, packages/testkit/src/__snapshots__/preeval.test.ts.snap, packages/testkit/src/preeval.test.ts, packages/utils/src/collectExportsAndImports.ts, packages/utils/src/findIdentifiers.ts, packages/utils/src/getScope.ts, packages/utils/src/isExports.ts, packages/utils/src/isRequire.ts, packages/utils/src/isUnnecessaryReactCall.ts, packages/utils/src/scopeHelpers.ts, packages/utils/src/visitors/JSXElementsRemover.ts
See #1055
Babel resolves the wrong scope for an `id` in a `FunctionDeclaration`. If the same `FunctionDeclaration` has a parameter with the same name as the id, that parameter will be resolved as a binding of identifier used as the function name.
=> fix(shaker): avoid collision between function name and its param

.changeset/curly-yaks-turn.md, docs/BUNDLERS_INTEGRATION.md, packages/webpack4-loader/package.json, packages/webpack4-loader/src/cache.ts, packages/webpack4-loader/src/index.ts, packages/webpack4-loader/src/outputCssLoader.ts, packages/webpack5-loader/src/cache.ts, packages/webpack5-loader/src/index.ts, packages/webpack5-loader/src/outputCssLoader.ts, pnpm-lock.yaml
When webpack is run with `--watch` or with `webpack-dev-server`, the generated css output will not be updated when dependencies imported into Linaria JavaScript source files, causing the resulting output to be stale.
The changes to the `ICache` interfaces are backward-compatible to avoid breaking any external implementations provided to the webpack builders using the prior versions of the interfaces.
This addresses #1077.
Webpack allows adding dependencies to modules. Since the `*.linaria.js` and `*.linaria.css` files need to be in sync in order to generate the correct changes in webpack's watch mode, the css loader needs to have access to that dependency list so that _it_ can tell webpack when it needs to change. The logical place for this was in the cache provider. But rather than …
=> fix(webpack): pass dependencies to cached css files

packages/babel/src/module.ts, packages/testkit/src/__fixtures__/ts-compiled-re-exports/constants.js, packages/testkit/src/__fixtures__/ts-compiled-re-exports/index.js, packages/testkit/src/module.test.ts
The `getOwnPropertyDescriptor` method of the exports proxy seems to be incorrect causing `export *` compiled to commonjs by the typescript compiler to not work.
Typescript will compile `export *` to the following:
```
var __exportStar = (this && this.__exportStar) || function(m, exports) {
for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
```
Because `getOwnPropertyDescriptor` always return an object the `hasOwnProperty` call will always return `true` causing no exports to get added.
Here is a cut down example of this causing issues when using linaria together with @fluentui/react https://stackblitz.com/edit/linaria-bug-nl1c3w
The only change made in this PR is to only return a property descriptor when the export …
=> fix: re-exports compiled by tsc not working

.changeset/purple-socks-allow.md, examples/vite/package.json, packages/babel/src/plugins/preeval.ts, packages/babel/src/transform-stages/1-prepare-for-eval.ts, packages/babel/src/transform.ts, packages/postcss-linaria/__tests__/locationCorrection.test.ts, packages/postcss-linaria/package.json, packages/rollup/src/index.ts, packages/stylelint-config-standard-linaria/package.json, packages/testkit/src/__snapshots__/preeval.test.ts.snap, packages/testkit/src/preeval.test.ts, pnpm-lock.yaml, website/package.json
See #1044
Vite injects some HMR-related code that cannot be evaluated by Linaria. Fortunately, that code can be safely removed.
=> fix(rollup): support for rollup@3 and vite@3 (fixes #1044, #1060)

.changeset/forty-crabs-itch.md, packages/babel/src/plugins/preeval.ts, packages/testkit/package.json, packages/testkit/src/__snapshots__/preeval.test.ts.snap, packages/testkit/src/preeval.test.ts, packages/testkit/src/utils/__snapshots__/removeWithRelated.test.ts.snap, packages/testkit/src/utils/removeWithRelated.test.ts, packages/utils/src/findIdentifiers.ts, packages/utils/src/index.ts, packages/utils/src/scopeHelpers.ts, pnpm-lock.yaml
Sometimes Linaria tries to remove a node from AST that is crucial for another node. Such cases produce errors like `Property name of JSXOpeningElement expected node to be of a type ["JSXIdentifier","JSXMemberExpression","JSXNamespacedName"] but instead got undefined`.
This PR introduces a common validator for all removing nodes that prevents such errors.
=> fix(shaker): get rid of "expected node to be of a type" errors

.changeset/little-moose-work.md, package.json, packages/react/package.json, pnpm-lock.yaml
Used version of `@emotion/is-prop-valid` didn't support ES modules, so that `@linaria/react` couldn't be imported in ES modules environment.
`@emotion/is-prop-valid` has been upgraded to the latest 1.2.0 version.
=> fix(react): upgrade @emotion/is-prop-valid to support ES modules

.changeset/many-beers-accept.md, packages/shaker/src/plugins/__tests__/__snapshots__/shaker-plugin.test.ts.snap, packages/shaker/src/plugins/__tests__/shaker-plugin.test.ts, packages/shaker/src/plugins/shaker-plugin.ts, packages/testkit/src/utils/__snapshots__/removeWithRelated.test.ts.snap, packages/testkit/src/utils/removeWithRelated.test.ts, packages/utils/src/scopeHelpers.ts
Shaker was too aggressive with the parameters of functions.
In terms of Babel, parameters are bindings. Shaker removes bindings if they aren't referenced anymore. However, Shaker should not remove parameters because it breaks code.
=> fix(shaker): do not remove params of functions if they aren't used

.changeset/wild-hairs-grin.md, packages/react/src/styled.ts
I've setup a minimal codesandbox with fixed package versions that should highlight the issue: https://codesandbox.io/p/sandbox/sharp-brook-3298j7?file=%2Fpages%2Findex.tsx
Use of the `styled` function in a next.js project causes a runtime exception seen in a stack trace here https://3298j7-3000.preview.csb.app
```
TypeError: validAttr is not a function
./node_modules/@linaria/react/dist/index.mjs (18:12)
```
Related: #1057 & #1093
It seems like a bug has been introduced after the support was added for esm exports in v4.2 where trying to import @emotion/is-prop-valid in @linaria/react
I've added a possible fix for this where we can pre-emptively transform the import before use in the module interop style, where we can check the typeof for the import and normalise the shape to `{default: …
=> fix(react): force interop check to fix @emotion/is-prop-valid esm import

.changeset/hip-kids-swim.md, packages/babel/src/plugins/preeval.ts, packages/babel/src/utils/collectTemplateDependencies.ts, packages/babel/src/utils/getTagProcessor.ts, packages/griffel/src/processors/makeStyles.ts, packages/react/__tests__/__snapshots__/styled.test.tsx.snap, packages/react/__tests__/styled.test.tsx, packages/react/package.json, packages/react/src/processors/styled.ts, packages/react/src/react-html-attributes.d.ts, packages/react/src/styled.ts, packages/tags/src/types.ts, packages/tags/src/utils/templateProcessor.ts, packages/testkit/src/__snapshots__/babel.test.ts.snap, pnpm-lock.yaml
See #968
In the ideal world, we can suppose that any lowercase string is the name of a built-in react component. Unfortunately, some custom components libraries don't respect the HTML spec and provide wrongly named components. To address this, I've inverted a custom component detection logic that now uses the list of known React components and enables property filtering only for those in that list.
=> fix(react): filter props only for known react tags (fixes #968)

README.md, docs/BUNDLERS_INTEGRATION.md
It seems like users struggle to find documentation on how to configure vite + typescript + linear #959
I added a simple vite configuration, and one that uses typescript.
I noted that `enforce: 'pre'` is added to the plugin in the example. I am not sure why so I omitted it in the examples. 
It could be useful to also add another entry in the [examples](https://github.com/callstack/linaria/tree/master/examples) directory, for vite + typescript + linear.
I don't think it will be interesting for the example to build the website ( as the website does not uses typescript ). Maybe include the source for a simple hello world page instead ?
=> docs: add vite configuration

.github/workflows/check.yml, .github/workflows/release.yml, .github/workflows/site-deploy.yml
For some reason, cache for _pnpm_ from `actions/setup-node@v3` doesn't work. It downloads modules every time again.
If you see logs from `pnpm install`, it takes much time to install: https://github.com/callstack/linaria/actions/runs/3504019849/jobs/5869437252#step:5:42
Packages: +1740 for 2m35s
However, using guide from [pnpm/action/setup](https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time) it works. I'm using it on my project:  https://github.com/MrFoxPro/bloki/actions/runs/3455571609/jobs/5767689037#step:7:12
Packages: +639 just for 4s.
I've added two tasks for cache for every CI task.
Cache will work after first successful run on branch.
=> chore(ci): set explicit pnpm cache

examples/gatsby/custom-config/package.json, examples/gatsby/plugin/package.json, package.json, packages/atomic/package.json, packages/babel/package.json, packages/cli/package.json, packages/core/package.json, packages/esbuild/package.json, packages/extractor/package.json, packages/griffel/package.json, packages/interop/package.json, packages/linaria/package.json, packages/logger/package.json, packages/postcss-linaria/package.json, packages/react/package.json, packages/rollup/package.json, packages/server/package.json, packages/shaker/package.json, packages/stylelint-config-standard-linaria/package.json, packages/stylelint/package.json, packages/tags/package.json, packages/utils/package.json, packages/webpack-loader/package.json, packages/webpack4-loader/package.json, packages/webpack5-loader/package.json, tsconfig.json, turbo.json
As this project now is based on pnpm, let's switch to pnpm. 
pnpm allows to skip `run` keyword when initiating command.
- Replaced `npm run` with `pnpm`.
- Fixed `watch` command in every package by concating build commands with `&`. I choose ampersand because it's almost cross-platform now: [Powershell 7+ supports it.](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-7.3#call-operator-) I've checked on Powershell 7.3.0.
- Deleted `watch` command from main `package.json`, because it floods memory.
- Deleted `baseBranch` property from turbo, as it does nothing.
- Set `preserveWatchOutput` in `tsconfig.json` because it does clearing output by default.
Let's run in CI.
=> chore: npm cmd to pnpm

examples/gatsby/plugin/package.json, packages/shaker/src/index.ts
Bug fix for #1061
Shaker used `transformSync` from the wrong babel version
=> fix(babel): avoid using different babel versions

.changeset/nice-cameras-move.md, packages/react/__dtslint__/styled.ts, packages/react/src/styled.ts
`styled` allowed to wrap components without props at all.
The new overload for 0-ary components was added.
=> fix(react): wrapped component should have className prop

packages/testkit/package.json, packages/testkit/src/collectExportsAndImports.test.ts, packages/utils/src/collectExportsAndImports.ts, pnpm-lock.yaml
Linaria tries to analyze each module dependency tree to prevent excess code evaluation. ES modules are pretty simple: every import, export and re-export is an AST node of a specific type. On the other hand, CJM is a mess: `require` is a common CallExpression, `export` is an identifier, list of imported tokens can be specified through destructuring assignment, which can also be transpiled to the bunch of function calls and temp identifiers. And the cherry on the cake is how different transpilers with different options (`babel`, `tsc`, `swc`) transpile ESM to CJM.
For now, Linaria officially supports `babel` and `tsc`. Code generated with other transpilers may work but cannot be optimized.
This PR introduces support for `swc`.
`swc->es5` and `swc->es2015` have been added as compilers for …
=> fix(babel): support code transpiled with swc

packages/esbuild/package.json, packages/rollup/package.json, pnpm-lock.yaml
See #1139
`esbuild` and `rollup` have been moved from `dependencies` to `devDependencies` and `peerDependencies`.
=> fix(esbuild,rollup): remove esbuild and rollup from dependencies (fixes #1139)

examples/esbuild/package.json, packages/esbuild/package.json, packages/esbuild/src/index.ts, pnpm-lock.yaml
When committing without `--no-verify`, syncpack run failed due to `✕ esbuild ^0.12.5, ^0.15.16`:
```
> umbrella@3.0.0-beta.19 sp:check /Users/chentsulin/oss/linaria
> syncpack
- @babel/cli ^7.19.3
- @babel/core ^7.20.2
- @babel/eslint-parser ^7.19.1
- @babel/generator ^7.20.4
- @babel/helper-module-imports ^7.18.6
- @babel/parser ^7.20.3
- @babel/plugin-proposal-class-properties ^7.18.6
- @babel/plugin-proposal-export-namespace-from ^7.18.9
- @babel/plugin-syntax-dynamic-import ^7.8.3
- @babel/plugin-syntax-jsx ^7.18.6
- @babel/plugin-syntax-typescript ^7.20.0
- @babel/plugin-transform-modules-commonjs ^7.19.6
- @babel/plugin-transform-runtime ^7.19.6
- @babel/plugin-transform-template-literals ^7.18.9
- @babel/preset-env ^7.20.2
- @babel/preset-react ^7.18.6
- @babel/preset-typescript …
```
=> fix(syncpack): use same esbuild version

.changeset/wet-cheetahs-approve.md, packages/server/__tests__/__snapshots__/collect.test.ts.snap, packages/server/__tests__/collect.test.ts, packages/server/src/collect.ts
Our codebase uses the [postcss-rtlcss](https://www.npmjs.com/package/postcss-rtlcss) package to add `.dir-ltr`, `.dir-rtl`, or `.dir` prefixes to our CSS selectors, so that most of them are in the following format:
```
.dir-ltr.otherClassname {
padding-bottom: 12px;
}
```
Since our HTML contains the `dir-ltr` class, when we use Linaria's `collect` function, a lot of unnecessary selectors are added to the critical CSS even though `otherClassname` is not present.
Also, we have media queries in this format:
```
@media(...) {
.dir-ltr.otherClassname {
padding-left: 12px;
}
.dir-rtl.otherClassname {
padding-right: 12px;
}
}
```
We want to specifically exclude the RTL selector when the direction is LTR and vice versa.
This PR proposes to add an opt-in `ignoredClasses` parameter to `collect` so …
=> feat: add ignored and excluded classes to critical CSS extraction in `collect`

.npmrc
When I cloned the project and installed it with pnpm, I got:
```
WARN  A pnpm-lock.yaml file exists. The current configuration prohibits to read or write a lockfile
```
I'm not familiar with pnpm, but I finally figure out it's due to the `lockfile` setting on my computer.
 
pnpm should respect the `pnpm-lock.yaml` file in the project whether lockfile is true or not out of the project scope.
```sh
$ npm config set lockfile false
$ git clone https://github.com/callstack/linaria.git
$ cd linaria && pnpm install
```
=> fix(pnpm): add lockfile = true to .npmrc

.changeset/sixty-peaches-rush.md, packages/vite/src/index.ts
Vite should replace import aliases so `resolve` functions in bundlers should be able to correctly resolve imports.
=> fix(vite): enforce: 'post'

docs/ATOMIC_CSS.md
This PR simply fixes a typo found in atomic css md file
=> docs: fix a typo in atomic css documentation

.changeset/new-seas-drive.md, packages/atomic/src/processors/css.ts
It's possible that no atomic styles are extracted from a css`` block. Regardless of whether this is a bug or not, we shouldn't crash the babel plugin/the build. 
To avoid this, check for undefined instead of truthiness, since empty string is falsy. 
tested locally with an empty css`` and this stops the crashing
=> Avoid crashing build on empty css``

docs/BUNDLERS_INTEGRATION.md
When using `@linaria/rollup` with vite, it does not work, however using `@linaria/vite` works like a charm!
=> Update @linaria/rollup to be @linaria/vite

.changeset/three-bikes-lay.md, .gitignore, docs/CONFIGURATION.md, packages/tags/src/TaggedTemplateProcessor.ts, packages/tags/src/utils/getVariableName.ts, packages/tags/src/utils/templateProcessor.ts, packages/tags/src/utils/types.ts, packages/testkit/src/__snapshots__/babel.test.ts.snap, packages/testkit/src/babel.test.ts, packages/utils/src/options/types.ts
Linaria generates `var()` with one argument - the variable itself. However, css variables can accept default value:
``` 
var( <custom-property-name> , <declaration-value>? ) 
```
Since there is no way to set default value for linaria's variable we limit functionality of css variables.
Using the variable names without `var()` wrapper will allow you to use it as-is. For example, it is useful for theming: (this example will work when `variableNameConfig` is `dashes` )
```
import { styled } from "@linaria/react";
export const Theme = styled.div`
--font-color: red;
`;
export const MyComponent = styled.div`
color: var(${(props) => props.color ?? ""}, var(--font-color));
`;
function App() {
return (
<Theme>
<MyComponent>Text with red color</MyComponent>
<MyComponent color="blue">Text with blue …
```
=> feat: option to remove `var()` wrapper around css variables

.changeset/calm-keys-jog.md, packages/babel/src/helper-module-imports.d.ts, packages/babel/src/utils/getTagProcessor.ts, packages/tags/src/BaseProcessor.ts, packages/utils/src/collectExportsAndImports.ts
This PR fixes the issue where the `addDefaultImport` and `addNamedImport` methods in processors always inserted ESM imports, even when the processed file used CommonJS. The updated code now correctly inserts the appropriate import for each file format.
=> fix(tags): use appropriate import/request for ESM/CommonJS

.changeset/wicked-poets-begin.md, packages/babel/src/transform-stages/helpers/loadLinariaOptions.ts, packages/babel/src/utils/processTemplateExpression.ts, packages/testkit/src/__fixtures__/sample-script.cjs, packages/testkit/src/module.test.ts
Fixes #1177.
This PR adds `.cjs` & `.mjs` to the list of default ones, so Linaria will handle them and load them properly.
```
linaria:module:00001 [eval-cache] ❌ module:00002 is going to be initialized +0ms
linaria:module:00002 [init] /private/var/folders/v4/l_41mr81261dpdvcdldkgdbh0000gn/T/nextjs-98284-78vGr91L2kUL/node_modules/@griffel/react/colors.cjs +1s
linaria:module:00002 [evaluated] the whole exports was overridden with '/private/var/folders/v4/l_41mr81261dpdvcdldkgdbh0000gn/T/nextjs-98284-78vGr91L2kUL/node_modules/@griffel/react/colors.cjs' +0ms
```
```
linaria:module:00001 [require] @griffel/react/colors.cjs -> /private/var/folders/v4/l_41mr81261dpdvcdldkgdbh0000gn/T/nextjs-98284-78vGr91L2kUL/node_modules/@griffel/react/colors.cjs +0ms
linaria:module:00001 [eval-cache] ❌ …
```
=> fix: handle .cjs & .mjs extensions

.changeset/itchy-eggs-impress.md, packages/babel/src/utils/getTagProcessor.ts, packages/tags/src/BaseProcessor.ts, packages/testkit/src/utils/getTagProcessor.test.ts
This pull request introduces the `tagSource` property for processors, which indicates the package and name of the imported processor. This information can be used to determine the correct package for inserted imports. This feature will improve the accuracy and maintainability of the project by ensuring that the correct package is used for inserted imports. It also makes it easier to understand the flow of data and debug any issues that may arise.
Existed tests were modified.
=> feat(tags): introduce tagSource for processors

.changeset/bright-coats-vanish.md, packages/shaker/src/plugins/__tests__/shaker-plugin.test.ts, packages/shaker/src/plugins/shaker-plugin.ts
shaker did not handle object pattern exports like `export const { foo, bar } = baz()`
The way that shaker associates exports seems to assume that the RHS of an export const assignment corresponds to exactly one export name. But this isn't true, as in the example above - `baz()`'s return will be destructured to multiple exported values. Due to this assumption, if one of the exports is not in `onlyExports`, the entire statement will be deleted. 
Added a unit test
=> fix: handle object patterns in exports

.changeset/shiny-owls-visit.md, packages/shaker/src/plugins/__tests__/shaker-plugin.test.ts, packages/shaker/src/plugins/shaker-plugin.ts, packages/testkit/src/module.test.ts, packages/utils/src/collectExportsAndImports.ts, packages/vite/src/index.ts
We found a weird bug when shaker attempted to operate on preact/compat. Note that it's probably a bug that shaker is even processing this file, since it means we didn't strip the import in an earlier stage, but I'm not sure what's going on there. 
I think the issue is demonstrated pretty clearly in the unit test, but the gist is that certain libraries might be packaged in a way where they have a `default` export, but no `__esModule: true` export. This will break babel's interopRequireDefault helper, which wraps its argument if it doesn't detect `__esModule: true`, resulting in an object like `{ default: { default: someExport } }`. 
In the case of preact/compat, this is fine, because all of the exports are *also* defined directly on `module.exports`. resulting in `{ default: { default: …
=> fix: workaround for weirdly packaged cjs modules

.changeset/weak-walls-behave.md, packages/shaker/src/plugins/__tests__/__snapshots__/shaker-plugin.test.ts.snap, packages/shaker/src/plugins/__tests__/shaker-plugin.test.ts, packages/shaker/src/plugins/__tests__/utils/shouldKeepSideEffect.test.ts, packages/shaker/src/plugins/shaker-plugin.ts, packages/shaker/src/plugins/utils/shouldKeepSideEffect.ts
Fixes #1189.
Generally there two kinds of side-effects:
- asset imports (`import './foo.css')
- real code ('import './foo')
We want to keep only imports that contain code. Implemented `shouldKeepSideEffect()` to check if an import should stay.
```js
shouldKeepSideEffect('regenerator-runtime') // true
shouldKeepSideEffect('./asset.css') // false
```
The tricky part is that `shouldKeepSideEffect('object.values')` is `false` 💥 However, we can't do much at this step: to be sure we need to resolve imports 🙃
New tests have been added.
=> fix: keep side effects from modules

.changeset/metal-hounds-push.md, packages/babel/package.json, packages/babel/src/transform-stages/helpers/loadLinariaOptions.ts, pnpm-lock.yaml
New vite projects (made with `pnpm create vite`, for example) have `"type": "module"` in `package.json`. That causes loading `linaria.config.js` to fail because of CJS/ESM mismatch.
Upgrade cosmiconfig to 8.x. The support for `.cjs` was added in 7.0.0 but no reason to hold back from version 8.
I updated the code for the breaking changes in cosmiconfig 6.x, see https://github.com/davidtheclark/cosmiconfig/blob/main/CHANGELOG.md#600
I don't think we need any new tests in linaria, it's probably sufficient that the existing tests continue to pass. Anything specific for `.cjs` would just reduplicate what cosmiconfig tests upstream.
=> fix(babel): update cosmiconfig so linaria.config.cjs works

packages/babel/src/plugins/preeval.ts, packages/testkit/src/__snapshots__/preeval.test.ts.snap, packages/testkit/src/preeval.test.ts
Fix some instances where preeval emits invalid code.
Avoid breaking builds due to buggy preeval logic. 
Unfortunately, babel seems to record identifiers as globals even when they're accessed via TS type references, e.g:
```
class Foo {
fetch: typeof global.fetch;
}
```
will result in `scope.hasGlobal('fetch')` returning true. preeval will end up deleting the class property, and then the entire class. The same applies if `fetch` is accessed in a member expression, e.g
```
class Foo {
fetch: typeof global.fetch;
constructor(options) {
this.fetch = options.fetch;
}
}
```
The key is the `typeof global.fetch` messes up Babel's scope tracking, which makes subsequent `isGlobal/isBrowserGlobal` return false positives. 
A similar problem occurs with TS type references - accessing `window.foo` or …
=> fix: preeval emits invalid code

.changeset/tender-guests-kick.md, packages/vite/src/index.ts
https://github.com/vitejs/vite/issues/11035#issuecomment-1416057700
It seems like Vite cannot resolve absolute paths on windows when the separator is `/` instead of `\`, so I tried normalizing the filename path output, and it works!
`npm run build` (`vite`) or `npm run build` (`vite build`) in this repo on a Windows machine: https://github.com/nstepien/vite-bug
=> Normalize import path in the Vite plugin to fix Vite builds on Windows

.changeset/bright-files-beg.md, packages/babel/src/module.ts
Vite in dev mode converts CJS libraries to ESM. In some unclear cases, it causes a situation when all exports from such modules are exported as an object under `default`.
This PR introduces a workaround that checks if an undefined import is presented in the `default` import. If so, the value from `default` will be returned.
However, the reason for such behaviour requires future investigation.
=> fix(vite): broken imports from some third-party libs

.changeset/purple-meals-deliver.md, packages/babel/src/transform-stages/1-prepare-for-eval.ts
See #1202 
This PR introduces a circuit breaker for cases when an imported dependency was already processed and presented in a resolve stack.
=> fix(babel): circular deps cause infinite loops (fixes #1202)

.changeset/metal-carrots-fix.md, packages/rollup/src/index.ts, packages/vite/src/index.ts
Linaria fails to transform code that contains external imports when used in rollup alongside certain plugins like node-resolve. See [this bug reproduction repo](https://github.com/kcover/linaria-rollup-resolve-repro) for an example.
The linaria rollup plugin as it exists expects any external imports to be resolved as 'null', and passes that along to the babel plugin, which knows to ignore such imports. It doesn't expect an object indicating an external dependency to be returned (See [the rollup resolveId hook docs](https://rollupjs.org/plugin-development/#resolveid) to see when this might occur). When that happens, the linaria plugin returns the `id` property of the object, which is often just the name of the import (e.g. 'react'). The babel-preset's transform function expects this to be …
=> fix(rollup): don't parse external libraries

.changeset/polite-chairs-float.md, packages/atomic/package.json
When using the latest version of yarn, you get the following warning about the missing peerDependency passthrough from `@linaria/react` => `@linaria/atomic`. I marked it as optional, since it appears that you would only need react if using the `styled` export.
Setting the following in my local yarnrc.yml resolves the warning
```yml
packageExtensions:
'@linaria/atomic@*':
peerDependencies:
react: '>=16'
peerDependenciesMeta:
react:
optional: true
```
=> fix(atomic): add react as an optional peerDependency

.changeset/unlucky-worms-complain.md, packages/babel/src/transform-stages/1-prepare-for-eval.ts
#1182 
Added a check to prepare-for-eval that will ignore json files. Another option would be to 
add the `.json` extension to the default regex for ignored files in [loadLinariaOptions](https://github.com/callstack/linaria/blob/master/packages/babel/src/transform-stages/helpers/loadLinariaOptions.ts#L40) but I'm not sure if that gets overridden by custom rules and I'm not sure we'd want that.
This isn't ready for merge yet because I've encountered a new error that I was hoping I could get some help with. See the read me in this [repo](https://github.com/kcover/babel-playground-app) I made to reproduce the issue.
Use the repo I linked above to reproduce the issue, then use `yarn link` to utilize this branch in that project and verify that the json parsing error no longer occurs.
=> fix(babel): do not parse json as js

packages/babel/src/transform-stages/helpers/loadLinariaOptions.ts
Windows compatibily.
One regexp used forward slashes only, while filenames have blackslashes on Windows.
Ran locally.
=> loadLinariaOptions: fix node_modules regexp for Windows

docs/BUNDLERS_INTEGRATION.md
Vite is present on the page but the link was missing in the "Jump to" list.
=> docs: add Vite to Bundlers table of contents

.changeset/proud-boats-study.md, packages/atomic/package.json, packages/atomic/src/css.ts, packages/atomic/tsconfig.json, packages/core/src/css.ts, packages/react/__tests__/__snapshots__/styled.test.tsx.snap, packages/react/__tests__/styled.test.tsx, packages/react/src/styled.ts, pnpm-lock.yaml
Prior to this pull request, using Jest with Linaria required the inclusion of a Babel plugin to extract styles and generate class names.
This pull request eliminates the need to include the @linaria/babel-preset when using Jest. All calls to styled and css will now be replaced with runtime versions that generate sequential class names. This simplification reduces the risk of configuration issues and streamlines the process of integrating Jest with Linaria.
=> fix(atomic,core,react): simplify Jest configuration

docs/CONFIGURATION.md
The default configuration of `rules` in `linaria.config.js` is inconsistent with the default configuration implemented in [the current code](https://github.com/callstack/linaria/blob/master/packages/babel/src/transform-stages/helpers/loadLinariaOptions.ts#L36). It needs to be updated, otherwise it will be confusing.
=> docs: update default settings for rules in config

.changeset/clean-berries-decide.md, packages/tags/src/utils/validateParams.ts
See #1227 
`isValidParams` has been rewritten without extends constraints.
=> fix(tags): typeScript < 4.7 compatibility (fixes #1227)

.changeset/empty-llamas-flow.md, packages/babel/src/utils/getTagProcessor.ts, packages/griffel/src/processors/makeStyles.ts, packages/react/src/processors/styled.ts, packages/tags/src/BaseProcessor.ts, packages/tags/src/TaggedTemplateProcessor.ts, packages/tags/src/types.ts, packages/testkit/src/utils/getTagProcessor.test.ts
See #1224 and #1214
The validation has been relaxed to support usages of `css` and `styled` in cases like `typeof styled`.
=> fix(tags): fix validation for css and styled tags

.changeset/thick-ads-beam.md, packages/react/src/styled.ts, packages/shaker/src/plugins/__tests__/__snapshots__/shaker-plugin.test.ts.snap, packages/shaker/src/plugins/__tests__/shaker-plugin.test.ts, packages/shaker/src/plugins/shaker-plugin.ts, packages/tags/src/TaggedTemplateProcessor.ts, packages/utils/src/collectExportsAndImports.ts
This pull request addresses the limitations in the existing shaker strategy, specifically in handling namespace imports and side effect imports. It aims to improve the efficiency and accuracy of the shaker process, while also fixing a bug related to file skipping. These enhancements will lead to better code optimization and reduced compile time.
This PR introduces the following changes:
1. Improves the search for specific imported values in namespace imports, ensuring that only correct values are identified and imported.
2. Adds shaker support for side effect imports.
3. Fixes an issue where certain files were being skipped, ensuring all relevant files are properly processed by the shaker.
=> fix(shaker): improve strategy for namespace imports and side effects

.changeset/blue-eagles-burn.md, docs/CONFIGURATION.md, packages/babel/src/transform-stages/helpers/loadLinariaOptions.ts
Some files in `node_modules` weren't detected as ESM. See #1242 
The regular expression used to detect the keywords `export` or `import` contained an error that resulted in a false negative for ESM files that did not have any imports.
=> fix(babel): fixed esm detection in node_modules

.changeset/esbuild-linaria-cant-find-module.md, packages/esbuild/src/index.ts
Fix: ERROR Cannot find module './style.js'
Found this error in the logs
```
[stage-1:async-resolve] ❌ cannot resolve ./style.js in /home/sebasjm/Work/linaria/src/SimpleButton.tsx: Error: Must specify "kind" when calling "resolve"
```
With these dependencies
```
"@linaria/core": "^4.2.10",
"@linaria/esbuild": "^4.2.11",
"@linaria/react": "^4.3.8",
"esbuild": "^0.17.19",
```
I checked the esbuild documentation and looks that there is a missing parameter. 
I patched locally and it worked for me.
I made a repo to reproduce and fix the problem 
https://github.com/sebasjm/linaria-esbuild-patch
=> Fix: ERROR Cannot find module 'xxx' with esbuild 0.17 and linaria 4.2

.changeset/strong-clouds-explode.md, packages/react/src/styled.ts
Fixes https://github.com/callstack/linaria/issues/1251
Adds a `process.env.NODE_ENV` check to `styled` when adding the `mocked-styled` classes, similar to how `css` is already doing.
Can be seen by checking the website build:
=> fix(react): don't add `mocked-styled` classnames outside test env

.changeset/vite-url-resolve.md, packages/vite/src/index.ts
[Relative path](https://vitejs.dev/guide/assets.html#importing-asset-as-url) in  css like: `url(../assets/img.png)` has been resolved error. This pr fixed it.
Vite support [relative path](https://vitejs.dev/guide/assets.html#importing-asset-as-url) in  css like: `url(../assets/img.png)`.
The `cssId` was previously resolved to `cssId`. Which may cause `../assets/img.png` resolve error.
So we should resolve the `cssId` to a file which is same directory of source file.
=> fix(vite): css `url()` resolve error

.changeset/nine-fans-walk.md, packages/shaker/src/plugins/__tests__/__snapshots__/shaker-plugin.test.ts.snap, packages/shaker/src/plugins/__tests__/shaker-plugin.test.ts, packages/utils/src/scopeHelpers.ts
Shaker hasn't properly processed expressions like `return (batch = newBatch)`. See @PierreGUI's comment [#1226 ](https://github.com/callstack/linaria/issues/1226#issuecomment-1599111723)
The reference detection algorithm has been improved.
A new test for that specific case was added.
=> fix(shaker): improved references detection

.changeset/serious-pans-pump.md, packages/babel/package.json, packages/babel/src/plugins/preeval.ts, packages/babel/src/utils/collectTemplateDependencies.ts, packages/babel/src/utils/getTagProcessor.ts, packages/griffel/src/processors/makeStyles.ts, packages/react/package.json, packages/react/src/index.ts, packages/react/src/processors/styled.ts, packages/react/src/styled.ts, packages/tags/src/types.ts, packages/testkit/src/__fixtures__/linaria-ui-library/components/index.js, packages/testkit/src/__fixtures__/linaria-ui-library/non-linaria-components.js, packages/testkit/src/__fixtures__/linaria-ui-library/package.json, packages/testkit/src/__fixtures__/non-linaria-ui-library/index.js, packages/testkit/src/__fixtures__/non-linaria-ui-library/package.json, packages/testkit/src/__snapshots__/babel.test.ts.snap, packages/testkit/src/babel.test.ts, packages/testkit/src/utils/getTagProcessor.test.ts, packages/utils/package.json, packages/utils/src/addIdentifierToLinariaPreval.ts, packages/utils/src/createId.ts, packages/utils/src/findPackageJSON.ts, packages/utils/src/index.ts, pnpm-lock.yaml
Breaking Change: Performance Optimization for `styled`
When a component is wrapped in `styled`, Linaria needs to determine if that component is already a styled component. To accomplish this, the wrapped component is included in the list of variables for evaluation, along with the interpolated values used in styles. The issue arises when a wrapped component, even if it is not styled, brings along a substantial dependency tree. This situation is particularly evident when using `styled` to style components from third-party UI libraries.
To address this problem, Linaria will now examine the import location of the component and check if there is an annotation in the `package.json` file of the package containing the components. This annotation indicates whether the package includes other …
=> feat(react): performance improvement

.changeset/four-cats-brush.md, packages/babel/src/utils/__tests__/collectTemplateDependencies.test.ts, packages/babel/src/utils/collectTemplateDependencies.ts, packages/babel/src/utils/getTagProcessor.ts, packages/tags/src/TaggedTemplateProcessor.ts, packages/tags/src/utils/templateProcessor.ts, packages/testkit/src/__snapshots__/babel.test.ts.snap, packages/testkit/src/babel.test.ts, packages/testkit/src/utils/extractExpression.test.ts
Variables in props-based interpolation functions are no longer required for the evaluation stage.
Here's an example:
```
import { getColor } from "very-big-library";
export const Box = styled.div\`
color: ${props => getColor(props.kind)};
\`;
```
In versions prior to and including 4.5.0, the evaluator would attempt to import `getColor` from `very-big-library`, despite it having no relevance to style generation. However, in versions greater than 4.5.0, `very-big-library` will be ignored.
A new test was added.
=> feat(react): optimisation for props-based interpolation

.changeset/nine-rings-learn.md, packages/vite/src/index.ts
Fixes fatal error in the Vite package: `transform` function fails to resolve paths correctly on Windows.
Fixes #1240 
- Convert Windows path separator `\` to `/`
Tested on my local Windows machine as working.
=> fix(vite): css `url()` windows-specific path resolve error (#1240)

.changeset/kind-roses-deny.md, packages/shaker/src/plugins/__tests__/shaker-plugin.test.ts, packages/testkit/src/__fixtures__/linaria-ui-library/types.ts, packages/testkit/src/__snapshots__/babel.test.ts.snap, packages/testkit/src/babel.test.ts, packages/utils/src/findIdentifiers.ts, packages/utils/src/isRemoved.ts
If a type is imported without a `type` annotation and is used in shaken code, its import will not be shaken. This may cause an unexpected increase in the evaluated code base.
A seemingly redundant check has been removed. I wish I had a better memory so I could remember why I used double protection to avoid finding identifiers in TS-related nodes. I hope both checks were redundant and were not used to prevent some unexpected behavior that is not covered by unit tests.
A new test has been added.
=> fix(babel): support type imports without `type` annotation

.changeset/stale-swans-raise.md, packages/babel/src/cache.ts, packages/babel/src/evaluators/index.ts, packages/babel/src/index.ts, packages/babel/src/plugins/babel-transform.ts, packages/babel/src/plugins/collector.ts, packages/babel/src/plugins/preeval.ts, packages/babel/src/transform-stages/1-prepare-for-eval.ts, packages/babel/src/transform-stages/2-eval.ts, packages/babel/src/transform-stages/3-prepare-for-runtime.ts, packages/babel/src/transform-stages/4-extract.ts, packages/babel/src/transform-stages/helpers/ModuleQueue.ts, packages/babel/src/transform-stages/helpers/loadLinariaOptions.ts, packages/babel/src/transform-stages/helpers/parseFile.ts, packages/babel/src/transform.ts, packages/babel/src/utils/processTemplateExpression.ts, packages/shaker/src/index.ts, packages/shaker/src/plugins/__tests__/shaker-plugin.test.ts, packages/shaker/src/plugins/shaker-plugin.ts, packages/testkit/src/__snapshots__/prepareCode.test.ts.snap, packages/testkit/src/module.test.ts, packages/testkit/src/prepareCode.test.ts, packages/utils/src/hasEvaluatorMetadata.ts, packages/utils/src/options/types.ts, packages/utils/src/types.ts
Sometimes Linaria tried to use the wrong Babel configs for parsing files.
`babel.loadOptions` is now used for every processed file, and the loaded config is reused for every transformation.
=> fix(babel): resolve babel config for every processed file

.changeset/stale-brooms-kick.md, .gitignore, packages/babel/src/plugins/preeval.ts, packages/babel/src/transform-stages/1-prepare-for-eval.ts, packages/babel/src/transform.ts, packages/cli/src/linaria.ts, packages/shaker/src/plugins/shaker-plugin.ts, packages/testkit/src/prepareCode.test.ts, packages/utils/src/EventEmitter.ts, packages/utils/src/debug/perfMetter.ts, packages/utils/src/index.ts, packages/vite/src/index.ts, packages/webpack5-loader/package.json, packages/webpack5-loader/src/LinariaDebugPlugin.ts, packages/webpack5-loader/src/index.ts, pnpm-lock.yaml, website/webpack.config.js
Improve debugging experience.
For the Vite plugin, a new option was added:
```
…
debug: {
filename: "linaria-debug.json",
print: true,
},
…
```
For Webpack, a new plugin was added:
```
const { LinariaDebugPlugin } = require('@linaria/webpack5-loader');
…
plugins: [
new LinariaDebugPlugin({
filename: 'linaria-debug.json',
print: true,
}),
…
]
…
```
=> feat: debug mode for Vite, and Webpack

.changeset/slimy-cougars-hammer.md, packages/babel/src/plugins/preeval.ts, packages/utils/src/addIdentifierToLinariaPreval.ts
See #1300 and #1287
Something destroys `data` inside the root scope, so preeval can't find saved `__linariaPreval` and recreates it with an empty list of expressions.
Another interesting undocumented feature of Babel.
=> fix(babel): use path.data instead of scope.data (fixes #1300)

.changeset/poor-chefs-share.md, packages/babel/src/cache.ts, packages/babel/src/evaluators/index.ts, packages/babel/src/index.ts, packages/babel/src/module.ts, packages/babel/src/transform-stages/1-prepare-for-eval.ts, packages/babel/src/transform-stages/helpers/ModuleQueue.ts, packages/babel/src/transform-stages/helpers/loadLinariaOptions.ts, packages/babel/src/transform.ts, packages/logger/src/index.ts, packages/testkit/src/__snapshots__/babel.test.ts.snap, packages/testkit/src/babel.test.ts, packages/testkit/src/module.test.ts, packages/testkit/src/prepareCode.test.ts
In some cases, a race condition happens, leading to "The expression evaluated to 'undefined'" error.
This PR introduces the new cache layer for tasks of imports resolver. Old cache layers were refactored.
A couple of new tests were added.
=> fix(babel): improved cache (fixes #1304 and #1287)

.changeset/kind-ligers-retire.md, packages/babel/src/module.ts, packages/babel/src/plugins/dynamic-import.ts, packages/babel/src/transform-stages/1-prepare-for-eval.ts, packages/testkit/src/__fixtures__/prepare-code-test-cases/dynamic-import/input.ts, packages/testkit/src/__snapshots__/prepareCode.test.ts.snap, packages/testkit/tsconfig.json
Fixes #1317.
The new plugin transforms `import()` to `__linaria_dynamic_import()` call. `__linaria_dynamic_import` is exposed on `Module` as a new field. This is very similar to implementation in Vite/vite-node.
=> feat: support dynamic imports for evaluation

.changeset/perfect-onions-play.md, packages/babel/src/index.ts, packages/babel/src/module.ts, packages/babel/src/transform.ts, packages/babel/src/transform/Entrypoint.helpers.ts, packages/babel/src/transform/actions/__tests__/actionRunner.test.ts, packages/babel/src/transform/actions/types.ts, packages/babel/src/transform/generators/baseProcessingHandlers.ts, packages/babel/src/transform/generators/index.ts, packages/babel/src/transform/generators/processEntrypoint.ts, packages/babel/src/transform/generators/transform.ts, packages/babel/src/transform/generators/workflow.ts, packages/babel/src/transform/helpers/withDefaultServices.ts, packages/babel/src/transform/types.ts, packages/testkit/src/__snapshots__/babel.test.ts.snap, packages/testkit/src/babel.test.ts
```
const url = "./__fixtures__/FOO";
const foo2 = require(url.toLowerCase()).foo2;
```
Dependencies missed during the preparation stage can now be handled during evaluation.
=> feat(babel): support for dynamic imports and requires

packages/babel/src/module.ts
This PR adds `.cjs` extension to `Module` in v3. It's required as new version of `@swc/helpers` uses export maps and points files to `.cjs`, for example:
```
"./_/_class_private_field_loose_key": {
"import": "./esm/_class_private_field_loose_key.js",
"default": "./cjs/_class_private_field_loose_key.cjs"
},
```
=> fix(module): add .cjs extension

.changeset/neat-worms-clean.md, packages/babel/src/transform/generators/getExports.ts, packages/babel/src/types.ts, packages/shaker/src/plugins/__tests__/shaker-plugin.test.ts, packages/shaker/src/plugins/shaker-plugin.ts, packages/testkit/src/collectExportsAndImports.test.ts, packages/utils/src/collectExportsAndImports.ts, packages/utils/src/index.ts
It appeared that the exports collector didn't correctly work with pure TS files and didn't process `export enum …` as an export.
`collectExportsAndImports` has been fixed to support TS-specific nodes. Also, better detection of reexports has been added.
A set of tests for TS has been added.
=> fix(utils): support for `export enum …` and transpiled reexports

.changeset/seven-windows-repeat.md, packages/utils/src/__tests__/__snapshots__/removeWithRelated.test.ts.snap, packages/utils/src/__tests__/removeWithRelated.test.ts, packages/utils/src/scopeHelpers.ts
Sometimes, dead code remover removes method declarations that may cause `is not a function` errors.
Code remover detects if an is-going-to-be-removed function is part of a prototype declaration and replaces it with a dummy function instead of removing it.
A new test was added.
=> fix(utils): prevent prototype methods from removing

.changeset/chilly-foxes-smash.md, packages/webpack5-loader/src/index.ts
Currently, Webpack loader resolves modules to CommonJS instead of ESM how it should, this PR fixes it.
=> fix(webpack-loader5): resolve to ES modules instead of CJS

.changeset/orange-islands-juggle.md, packages/testkit/src/collectExportsAndImports.test.ts, packages/utils/src/collectExportsAndImports.ts
The exports finder didn't support enums that were transpiled to ESM by tsc.
=> fix(utils): fix exports finder for enum that were transpilled with tsc

packages/babel/src/transform/BaseEntrypoint.ts, packages/babel/src/transform/Entrypoint.helpers.ts, packages/babel/src/transform/Entrypoint.ts, packages/babel/src/transform/__tests__/createEntrypoint.test.ts, packages/babel/src/transform/generators/__tests__/processEntrypoint.test.ts, packages/babel/src/transform/generators/processEntrypoint.ts, packages/babel/src/transform/generators/workflow.ts, packages/babel/src/types.ts, packages/shaker/src/plugins/shaker-plugin.ts, packages/testkit/src/__fixtures__/loop/a.js, packages/testkit/src/__fixtures__/loop/ab.js, packages/testkit/src/__fixtures__/loop/b.js, packages/testkit/src/__fixtures__/loop/ba.js, packages/testkit/src/__fixtures__/loop/index.js, packages/testkit/src/__fixtures__/self-import.js, packages/testkit/src/__snapshots__/babel.test.ts.snap, packages/testkit/src/babel.test.ts, packages/testkit/src/collectExportsAndImports.test.ts, packages/utils/src/collectExportsAndImports.ts
When two concurrent tasks try to process two files that have circular imports to each other, a build fails with a stack overflow error or goes into an endless cycle.
This PR introduces a better cycle detection algorithm.
A couple of new tests were added.
=> fix(babel): endless loop and stack overflow

.changeset/lovely-moles-laugh.md, docs/CONFIGURATION.md, packages/babel/src/module.ts, packages/babel/src/vm/createVmContext.ts, packages/testkit/src/module.test.ts, packages/utils/src/options/types.ts
Some usages of global APIs cannot be eliminated by the shaker and may lead to errors during the evaluation stage.
This pull request introduces a new option called `overrideContext`, which can be used to inject global variables into an evaluation context of all or specific modules. This allows for mocking non-implemented APIs and prevents the build from crashing.
One new test was added.
=> feat(babel): overrideContext option

.changeset/lovely-moles-laugh.md, .changeset/plenty-mice-fry.md, docs/CONFIGURATION.md, packages/babel/src/module.ts, packages/babel/src/vm/createVmContext.ts, packages/shaker/src/plugins/__tests__/__snapshots__/shaker-plugin.test.ts.snap, packages/shaker/src/plugins/__tests__/shaker-plugin.test.ts, packages/shaker/src/plugins/shaker-plugin.ts, packages/testkit/src/module.test.ts, packages/utils/src/options/types.ts, packages/utils/src/removeDangerousCode.ts
See #1308
1. declares `$RefreshReg$` as a dangerous global API that should be removed before evaluation;
2. fixes an issue with the shaker that sometimes couldn't find bindings in default exports.
=> fix(shaker): process functions and classes definitions in default exports (fixes #1308)

.changeset/seven-fishes-exist.md, packages/babel/src/vm/createVmContext.ts
See #1345
Vitests uses deprecated GlobalWindow, and so do we.
=> fix(babel): happy-dom doesn't work on Stackblitz (fixes #1345)

.changeset/pretty-horses-behave.md, .changeset/six-elephants-design.md, packages/utils/src/__tests__/__snapshots__/removeDangerousCode.test.ts.snap, packages/utils/src/__tests__/__snapshots__/removeWithRelated.test.ts.snap, packages/utils/src/__tests__/removeDangerousCode.test.ts, packages/utils/src/__tests__/removeWithRelated.test.ts, packages/utils/src/removeDangerousCode.ts, packages/utils/src/scopeHelpers.ts
See #1310 
The code remover is trained to handle logical and ternary expressions:
- `opts.hostname || location.hostname` -> `opts.hostname`
- `typeof location !== "undefined" ? location.hostname : "localhost"` -> `typeof location !== "undefined" ? undefined : "localhost"`
- `location.hostname ? "location.hostname" : "localhost"` -> `"localhost"`
It also handles some popular 'is-it-browser' checks like `typeof window !== 'undefined'` or `typeof location !== 'undefined'` and removes unreachable branches in `if` statements.
A couple of new tests were added.
=> fix(utils): logical and ternary expressions in code remover (fixes #1310)

.changeset/gorgeous-jobs-approve.md, packages/utils/src/__tests__/__snapshots__/removeDangerousCode.test.ts.snap, packages/utils/src/__tests__/removeDangerousCode.test.ts, packages/utils/src/scopeHelpers.ts
Broken compatibility with socket.io. See #1310
Shaker was too aggressive and removed classes when any member of it was deleted.
=> fix(utils): code remover should not delete classes if any member was deleted

.changeset/short-cats-travel.md, docs/FEATURE_FLAGS.md, packages/babel/src/transform/Entrypoint.helpers.ts, packages/babel/src/transform/helpers/loadLinariaOptions.ts, packages/testkit/src/babel.test.ts, packages/testkit/src/module.test.ts, packages/utils/src/options/types.ts
It wasn't a good idea to always resolve `.babelrc` for every parsed file.
The new feature flag `useBabelConfigs` has been added. The default value is `true` but will be changed to `false` in the next major release. 
One new test was added.
=> feat(babel): introduces `useBabelConfigs` feature flag

.changeset/pretty-mugs-try.md, examples/webpack4/package.json, examples/webpack5/package.json, packages/testkit/src/__snapshots__/prepareCode.test.ts.snap, packages/testkit/tsconfig.json, packages/utils/src/options/loadBabelOptions.ts, pnpm-lock.yaml
Partially fixes #1348.
In cases when `@babel/preset-env` is used in user configs (for example, `.babelrc`) and they don't have explicit `modules: false`, we will have to deal with CJS instead of ESM.
To solve this, we need to specify caller params to avoid CJS transforms:
https://github.com/babel/babel/blob/e0375121bfea96d277f49543dc543f116523cfd0/packages/babel-preset-env/src/index.ts#L270-L283
- Caller's config is updated
- Versions in `package.json` files are fixed
=> fix: add caller settings to loadBabelOptions()

.changeset/five-queens-scream.md, packages/shaker/src/plugins/__tests__/__snapshots__/shaker-plugin.test.ts.snap, packages/shaker/src/plugins/__tests__/shaker-plugin.test.ts, packages/shaker/src/plugins/shaker-plugin.ts, packages/utils/src/scopeHelpers.ts, turbo.json
See #1348 
Slightly reworked shaker for the specific case with CJS-export assigned to a const.
=> fix(shaker): an issue with assigned exports (fixes #1348)

.changeset/orange-baboons-reflect.md, packages/vite/src/index.ts
See #1246
If the resolver meets a file that is resolved but doesn't exist, it calls `optimizeDeps`, so Vite will forcefully create it.
=> fix(vite): issue with dev mode and deoptimized deps (fixes #1246)

.changeset/great-seahorses-talk.md, packages/babel/src/transform/Entrypoint.helpers.ts, packages/testkit/src/__snapshots__/babel.test.ts.snap, packages/testkit/src/babel.test.ts
See #1353
Built-in modules are handled in `Module.require`, and we don't need their source code, so we can skip the reading step.
One new test has been added.
=> fix(babel): do not try to read built-in modules

.changeset/afraid-starfishes-film.md, .changeset/tall-clouds-reply.md, packages/babel/src/evaluators/index.ts, packages/babel/src/module.ts, packages/babel/src/plugins/babel-transform.ts, packages/babel/src/transform.ts, packages/babel/src/transform/Entrypoint.helpers.ts, packages/babel/src/transform/Entrypoint.ts, packages/babel/src/transform/Entrypoint.types.ts, packages/babel/src/transform/__tests__/entrypoint-helpers.ts, packages/babel/src/transform/generators/collect.ts, packages/babel/src/transform/generators/evalFile.ts, packages/babel/src/transform/generators/transform.ts, packages/babel/src/transform/helpers/loadLinariaOptions.ts, packages/babel/src/transform/types.ts, packages/testkit/src/module.test.ts, packages/testkit/src/prepareCode.test.ts
In some cases `pluginOptions` can be lost.
Now, the actual version of `pluginOptions` is stored in the Services collection. `pluginOptions` from `Entrypoint` has been deleted.
=> fix(babel): lost plugin options

.changeset/fifty-plums-poke.md, packages/react/src/styled.ts
Old babel-loader in webpack 4 has problems with parsing `@linaria/react`
The nullish coalescing operator has been replaced with good old &&.
=> fix(react): unexpected token in @linaria/react

.changeset/grumpy-flowers-watch.md, packages/atomic/package.json, packages/atomic/src/processors/helpers/atomize.ts, packages/babel/package.json, packages/babel/src/transform/generators/extract.ts, packages/testkit/src/__snapshots__/babel.test.ts.snap, pnpm-lock.yaml
Stylis v4 is faster than v3, and fixes misbehaviors in the older version regarding nested pseudo-classes.
Fixes #649 
Update stylis in both the babel and atomic packages.
The changes are pretty straightforward. In the atomic package, rather than configure stylis keyframes/prefix, we simply omit those middlewares for the same effect.
This is a (slightly) breaking change, and the commit is marked as such. In particular, stylis v4 handles nested pseudo-classes differently from v3. The old version joined `.x { :is(.y) }` to `.x:is(.y)` whereas the new version separates them `.x :is(.y)`. The new behavior matches how SCSS and other preprocessors work. Linaria consumers will need to check and possibly update their styles for the new behavior.
Ran all the tests and updated snapshots:
- The babel …
=> feat: upgrade stylis to v4

.changeset/seven-insects-study.md, packages/tags/src/utils/templateProcessor.ts, packages/testkit/src/__snapshots__/babel.test.ts.snap, pnpm-lock.yaml
See #1141 and #1368
`lastTemplateElementLocation` attempted to track end of previous template element, but it failed to update for expressions. On review, it seems that `lastTemplateElementLocation` isn't necessary at all, since `ex.loc.start` contains the necessary location.
It is possible that I misunderstood the motivation for `lastTemplateElementLocation` but it hasn't been clear to me yet.
There was already a failing test case for this added in #1151. This PR fixes that snapshot.
=> fix: space inserted after function interpolation (fixes #1141 #1368)

packages/postcss-linaria/src/parse.ts
@linaria/postcss-linaria can not parse something like this:
```
styled(Button)`
width: 50px;
`
```
=> fix: @linaria/postcss-linaria cannot parse styled(Button)`` properly

.changeset/lemon-parents-accept.md, packages/postcss-linaria/src/stringify.ts, packages/postcss-linaria/src/util.ts
Fixes #1074
Cases:
```js
css`
height: ${(props) => props.size}px;
transform: translate(${tokens.spacing1}, calc(${tokens.spacing2} + ${tokens.spacing3}));
@media (max-width: ${breakpoints.desktop}) {
font-size: 1.15rem;
}
.${SomeStyle} & {
align-items: center;
}
&.${SomeStyle} {
align-items: center;
}
`;
```
=> Fix the expressions in at-rule parameters and rules with functions

.github/workflows/check.yml, .github/workflows/main.yml, .github/workflows/release.yml, .github/workflows/site-deploy.yml
- Please update the following actions to use Node.js 20:actions/checkout@v2,actions/checkout@v3, pnpm/action-setup@v2, actions/setup-node@v3, actions/cache@v3.
- For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
=> chore: update actions to latest versions

.changeset/quick-suns-help.md
All packages should use wyw@0.5.2, not only `react`. Fixes #1407
It's just the changeset.
=> fix: Update wyw-in-js to 0.5.3

packages/stylelint/package.json, packages/stylelint/src/preprocessor.ts, packages/testkit/package.json, packages/testkit/src/babel.test.ts, pnpm-lock.yaml
One less dependency :D
* Removes dependency on strip-ansi in favor of built-in util
* Bumps engines.node from 16.0.0 to 16.11.0
tests pass locally
```
Tasks:    30 successful, 30 total
Cached:    10 cached, 30 total
Time:    42.261s 
```
=> refactor: remove strip-ansi

.changeset/funny-meals-brake.md, package.json, packages/react/src/styled.ts, pnpm-lock.yaml
React has removed the `JSX` global namespace in React 19, as a result, it needs to be accessed via the React global namespace now `React.JSX`.
Access JSX via React.JSX.
=> fix: use `React.JSX` instead of `JSX` for React 19 support
