- package.json
This fixes import rewiring couldn't resolve to `linaria` from linked modules.
cc @satya164
> fix: link linaria to itself so it's able to resolve

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
Thanks to @thymikee for `Contributing.md` guide
> doc: Add more badges, CoC and Contributing guide

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
> Add Issue and PR templates

- docs/DYNAMIC_STYLES.md
**Summary**
Little typo on `DYNAMIC_STYLES.md` file.
> Fix DYNAMIC_STYLES doc typo

- website/src/App.js
**Summary**
Updated example link on website footer. Also, the website now is using Preact, so I changed that too.
Fix #104
> website: Fix example link

- README.md
> remove + sign for users simple copy and paste

- src/__tests__/css.spec.js
- src/babel/lib/__tests__/errorUtils.spec.js
- src/babel/lib/__tests__/moduleSystem.spec.js
- src/babel/lib/errorUtils.js
- src/babel/lib/moduleSystem.js
- src/css.js
> css.named validation

- docs/BABEL_PRESET.md
**Summary**
Describes how to setup Linaria with CRA and Next.js.
I'm ok with moving it somewhere else.
> chore: provide example config with CRA and Next.js

- README.md
**Summary**
Just published [`linaria-jest`](https://github.com/thymikee/linaria-jest) with React and Preact snapshot serializer, so adding a reference to readme.
Fixes #98
> Add `linaria-jest` to readme

- CONTRIBUTING.md
Just updating the Callstack name (no .io anymore) and link it to webpage.
> Update Callstack name and link in CONTRIBUTING

- package.json
> Publish stylelint-config and stylelint-preprocessor

- README.md
> Add gatsby-plugin-linaria to recommended libraries

- .release-it.json
- package.json
- yarn.lock
with 'release-it', we can bump version automatically, tag the commit, create a new release on GitHub with a proper changelog, and npm publish all with one command.
> chore: setup automated release

- src/babel/evaluate.js
> Make Module.transform configurable from evaluate

- src/__tests__/__snapshots__/babel.test.js.snap
- src/__tests__/__snapshots__/preval.test.js.snap
- src/__tests__/babel.test.js
- src/__tests__/preval.test.js
- src/babel/extract.js
> fix: check if import is from linaria

- README.md
- docs/BABEL_PRESET.md
- docs/BUNDLERS_INTEGRATION.md
- docs/HOW_IT_WORKS.md
- flow-typed/npm/rollup-pluginutils_v2.x.x.js
- package.json
- rollup.js
- src/rollup.js
- yarn.lock
Added Rollup plugin and updated docs.
> feat: add Rollup plugin

- .babelrc
- package.json
- src/__tests__/__snapshots__/preval.test.js.snap
- src/__tests__/__snapshots__/styled.test.js.snap
- src/__tests__/preval.test.js
- src/__tests__/styled.test.js
- src/react/styled.js
- yarn.lock
React supports using class instead of className. we should too.
>  fix: support class prop

- package.json
- src/__tests__/__snapshots__/babel.test.js.snap
- src/__tests__/__snapshots__/preval.test.js.snap
- src/__tests__/babel.test.js
- src/__tests__/preval.test.js
- src/babel/extract.js
- src/react/styled.js
- yarn.lock
> feat: throw error for invalid interpolations at build-time to avoid mistakes

- .circleci/config.yml
- package.json
- src/__fixtures__/escape-character.js
- src/__tests__/__snapshots__/babel.test.js.snap
- src/__tests__/__snapshots__/preval.test.js.snap
- src/__tests__/babel.test.js
- src/__tests__/preval.test.js
- src/__tests__/transform.test.js
- src/babel/extract.js
See [6f6102a](https://github.com/callstack/linaria/pull/309/commits/6f6102a44eee3c93656bd5e0e20ecab0037ba666) for a small diff without indentation changes
>  feat: drop unused CSS from output

- src/__tests__/__snapshots__/babel.test.js.snap
- src/__tests__/__snapshots__/preval.test.js.snap
- src/__tests__/babel.test.js
- src/__tests__/preval.test.js
- src/babel/extract.js
> feat: determine display name from file name

- src/babel/module.js
- src/loader.js
**Summary**
It just allows using jsx files in additional to tsx.
> fix: add .jsx to the list of default extensions

- src/__tests__/__snapshots__/preval.test.js.snap
- src/__tests__/preval.test.js
- src/babel/evaluate.js
> fix: strip sequence expression when evaluating [WIP]

- docs/BASICS.md
Properly escaping back-tick in docs
Markdown formatting was not proper to display the single back-tick character on GitHub
> Properly escaping back-tick in docs

- .circleci/config.yml
**Summary**
Let's not spawn Flow server on CI
**Test plan**
Flow fixed
> chore: Use flow check on CI

- src/babel/index.js
- src/cli.js
- src/transform.js
> feat: add support for config option in the CLI

- src/__tests__/__snapshots__/babel.test.js.snap
- src/__tests__/__snapshots__/preval.test.js.snap
- src/__tests__/babel.test.js
- src/__tests__/preval.test.js
- src/babel/extract.js
> feat: handle arrays in interpolations

- README.md
**Summary**
Giving more recognition to Callstack :)
**Test plan**
See README
> docs: add callstack-badge and a note to the readme

- src/babel/evaluate.js
- src/babel/extract.js
- src/babel/index.js
- src/babel/types.js
- src/babel/utils/loadOptions.js
- src/babel/visitors/TaggedTemplateExpression.js
- src/rollup.js
- src/transform.js
> fix: load config file before parsing

- .release-it.json
- package.json
- yarn.lock
**Summary**
As I was working on release-it v11, I tried a few projects in the wild and yours was one of them. So why not open a PR if I have the changes already :)
**Test plan**
You can check out my PR and run `npm run release` (without actually releasing) to see whether it does the job for you.
> Migrate to release-it v11

- src/babel/evaluate/shaker.ts
> fix: no filename was passed to Babel (#428)

- package.json
- src/core/css.ts
- yarn.lock
> fix: incorrect type for `css` (#429)

- docs/DYNAMIC_STYLES.md
**Summary**
Docs typo fixes
**Test plan**
:man_shrugging:
> [docs]: remove bad imports in code samples

- README.md
Works wonderful with https://github.com/styled-components/webstorm-styled-components.
> docs: add Webstorm in Editor Plugins section

- docs/THEMING.md
change in docs theming class to className
> docs: change class to className

- README.md
>  docs: change class to className

- src/__tests__/__snapshots__/preval.test.ts.snap
- src/__tests__/__snapshots__/transform.test.ts.snap
- src/__tests__/depsGraph.test.ts
- src/__tests__/evaluators/__snapshots__/shaker.test.ts.snap
- src/__tests__/evaluators/shaker.test.ts
- src/__tests__/preval.test.ts
- src/__tests__/transform.test.ts
- src/babel/evaluators/shaker/DepsGraph.ts
- src/babel/evaluators/shaker/GraphBuilderState.ts
- src/babel/evaluators/shaker/Visitors.ts
- src/babel/evaluators/shaker/dumpNode.ts
- src/babel/evaluators/shaker/graphBuilder.ts
- src/babel/evaluators/shaker/identifierHandlers.ts
- src/babel/evaluators/shaker/index.ts
- src/babel/evaluators/shaker/langs/core.ts
- src/babel/evaluators/shaker/scope.ts
- src/babel/evaluators/shaker/shaker.ts
- src/babel/evaluators/shaker/types.ts
**Summary**
This is the last part of PR #462. It introduces the shaker as a second evaluation plugin.
**Test plan**
> Shaker evaluation strategy

- README.md
Plenty of people [looking for a way to use Linaria without ejecting](https://github.com/callstack/linaria/issues?utf8=%E2%9C%93&q=is%3Aissue+cra). This [craco plugin](https://github.com/jedmao/craco-linaria) fulfills that need.
> docs: add craco-linaria plugin to README

- src/babel/visitors/TaggedTemplateExpression.js
Possible fix, not sure if this should be solved further upstream, in css tagged template bit?
> Fix #475: error on escaped unicode character

- src/cli.js
**Summary**
Closes #395 
**Test plan**
> Fix ts cli support

- docs/BASICS.md
**Summary**
The current link is broken 😭 
**Test plan**
IDK 😸
> docs(BASICS): fix a link to MDN article

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/question.md
My previous PR introduced some formating issue for bug issue template
issue template settings are YAML file, I used some validator and fixed it :D
I copy-pasted new versions in file editor on Github,  it recognizes bug template correctly
> docs: fix issues with templates

- src/__tests__/module.test.ts
- src/babel/module.ts
Some variables available in global scope are not included by default in vm context See #562 
green CI
> Added more variables when vm context is created

- src/loader.ts
Closes #359 
If a file is imported from a directory above the project root, it will be saved in the cache with an absolute path. It cannot be a part of a former relative path because of potential naming collisions.
Additionally, I added support for detecting the Lerna monorepo project root next to the existing detection of yarn workspaces project root.
I tested it manually on an example project
> fix(webpack): cache directory for modules above project root, support lerna root

- docs/CONFIGURATION.md
- docs/HOW_IT_WORKS.md
A few grammar mistakes corrected
> patch: issue 566

- docs/CONFIGURATION.md
Link is broken
Fixed the link to correctly point to evaluators in how it works.
> [doc] fix broken link

- src/__tests__/detect-core-js.test.js
- src/__tests__/transform.test.ts
- src/transform.ts
- yarn.lock
There was a bug with transforming file that contains only unused linaria code( like variables that never were used again)
Fixes #624
Transformer returns
Added tests for this case.
> Transformer returns always transformed code if file contains only unused linaria code

- src/react/styled.ts
There were last usage of rest operator which caused issues without additional transpliling linaria on the user side.
Fixes #618 
green CI
> Removed rest operator from styled

- docs/BUNDLERS_INTEGRATION.md
This PR fixes the links to the svelte configs in `BUNDLERS_INTEGRATION.md`.
> docs: fix links for Svelte configs

- packages/babel/src/extract.ts
Typo in the unexpected runtime error message is fixed by this PR.
I tried `yarn run check:all`. The result is no error.
> fix: fix typo in the error message

- .release-it.json
- lerna.json
- package.json
- packages/babel/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/extractor/package.json
- packages/linaria/babel/package.json
- packages/linaria/evaluators/package.json
- packages/linaria/loader/package.json
- packages/linaria/package.json
- packages/linaria/react/package.json
- packages/linaria/rollup/package.json
- packages/linaria/server/package.json
- packages/linaria/stylelint-config/package.json
- packages/logger/package.json
- packages/preeval/package.json
- packages/react/package.json
- packages/rollup/package.json
- packages/server/package.json
- packages/shaker/package.json
- packages/stylelint/package.json
- packages/webpack4-loader/package.json
- website/package.json
- yarn.lock
Just a branch with release-related configs.
> The first release of monorepo

- docs/BASICS.md
Fixes small typo in `docs/BASIC.md`
> docs: fix typo

- packages/extractor/package.json
- packages/extractor/src/index.ts
- packages/shaker/package.json
- packages/shaker/src/index.ts
- yarn.lock
> fix(babel): use require.resolve for resolve babel plugins (#700)

- packages/cli/package.json
- packages/cli/src/cli.ts
resolve issue #731 and #732 
see detail in issue #731 and #732
> fix: resolve output filename relative to source root, use valid bin field

- src/transform.ts
Back ports the change in https://github.com/callstack/linaria/pull/737 to linaria `v2`. For motivation please see previous PRs description. It would be awesome if we could have this merged and released sometime this week!
```
- Moved logic for extracting CSS from the AST into
a `extractCssFromAst()` function and exported it from `transform.ts`
- Moved logic for determining whether to run AST analysis and CSS
extraction into a `shouldTransformCode()` function and exported it
```
> feat(babel): expose CSS extraction from AST logic

- docs/BUNDLERS_INTEGRATION.md
> Fixes a typo in README

- docs/HOW_IT_WORKS.md
[debugging section of Contributing docs](https://github.com/callstack/linaria/blob/master/docs/CONTRIBUTING.md#debugging-and-deep-dive-into-babel-plugin) link is broken.
update new link! 😀
> docs: update contributing docs link

- packages/webpack4-loader/src/index.ts
- packages/webpack5-loader/src/index.ts
This is a fix for #658 and other related bugs
Now all options are passed down to loader.
> fix(webpack): pass all user resolve options to loader (fixes #658)

- README.md
Styled-components has moved, so the current link to vscode-styled-components is old and navigates to the not-found page.
> Styled Components has moved! Make sure you're downloading it from here: https://marketplace.visualstudio.com/items?itemName=styled-components.vscode-styled-components. The jpoissonnier.vscode-styled-components version will recieve no more updates.
https://marketplace.visualstudio.com/items?itemName=jpoissonnier.vscode-styled-components
https://marketplace.visualstudio.com/items?itemName=styled-components.vscode-styled-components
Update the link to vscode-styled-components.
Click the new link and make sure it navigates to the vscode-styled-components page instead of the not-found page.
> docs: update the link to vscode-styled-components

- docs/API.md
Missing conjuction in the API.md file
> fix(api.md)missing conjuction

- docs/ATOMIC_CSS.md
> docs(atomic): fix typo

- packages/webpack5-loader/src/index.ts
This line does nothing ¯\_(ツ)_/¯
> chore: remove useless line in webpack5-loader

- .changeset/purple-stingrays-carry.md
- .changeset/shaggy-hats-lay.md
- packages/babel/src/transform-stages/1-prepare-for-eval.ts
- packages/babel/src/transform-stages/3-prepare-for-runtime.ts
- packages/testkit/src/__snapshots__/babel.test.ts.snap
- packages/testkit/src/babel.test.ts
- packages/utils/src/scopeHelpers.ts
> fix(babel): avoid unnecessary babel transformations

- .changeset/tender-actors-yawn.md
- packages/utils/src/scopeHelpers.ts
> fix(babel): property key of ClassMethod expected to be (fixes #1030)

- .changeset/popular-trainers-kneel.md
- packages/webpack4-loader/src/index.ts
- packages/webpack5-loader/src/index.ts
> fix(webpack): fix webpack crash when an error in Linaria happens

- packages/shaker/src/index.ts
> fix(shaker): remove envName from babel options

- docs/CONFIGURATION.md
`classNameSlug` has the third argument `args`. It contains a lot of useful properties that can help with building selectors.
> docs: enhanced documentation for classNameSlug config

- .changeset/seven-clouds-yell.md
https://www.npmjs.com/package/@linaria/postcss-linaria doesn't show a readme despite being added in https://github.com/callstack/linaria/pull/1107
According to the [npmjs.com docs](https://docs.npmjs.com/about-package-readme-files), the package has to be bumped in order for the readme to get updated. 
N/A
> update patch version of linting packages to npm will pick up change

- .changeset/soft-windows-arrive.md
> chore(vite): fix typo path -> patch

- .changeset/shaggy-onions-deny.md
- packages/testkit/package.json
- packages/testkit/src/collectExportsAndImports.test.ts
- packages/utils/src/collectExportsAndImports.ts
- packages/utils/src/isExports.ts
- packages/utils/src/isGlobal.ts
- packages/utils/src/isRequire.ts
- pnpm-lock.yaml
The same as #1138 but for esbuild
> fix(babel): support code transpiled with esbuild

- .changeset/fresh-mayflies-talk.md
- packages/vite/package.json
- packages/vite/src/index.ts
fixes https://github.com/callstack/linaria/issues/1105
> fix(vite): fix id resolution

- packages/babel/src/cache.ts
- packages/babel/src/evaluators/index.ts
- packages/babel/src/index.ts
- packages/babel/src/module.ts
- packages/babel/src/plugins/babel-transform.ts
- packages/babel/src/transform-stages/1-prepare-for-eval.ts
- packages/babel/src/transform-stages/2-eval.ts
- packages/babel/src/transform.ts
- packages/babel/src/types.ts
- packages/cli/src/linaria.ts
- packages/rollup/src/index.ts
- packages/testkit/src/module.test.ts
- packages/vite/src/index.ts
Change repetition of multiple caches with one object.
> refactor: implement TransformCacheCollection

- .changeset/grumpy-feet-arrive.md
- examples/astro-solid/package.json
- packages/vite/package.json
- pnpm-lock.yaml
Allow Vite 4+ as it just works.
> chore(vite): allow vite v4

- packages/testkit/src/__snapshots__/babel.test.ts.snap
- packages/testkit/src/babel.test.ts
See https://github.com/callstack/linaria/issues/1141
Add a testcase to demonstrate the issue
```ts
it('handles interpolation in css function followed by unit', async () => {
const { code, metadata } = await transform(
dedent`
import { styled } from '@linaria/atomic';
const size = 200;
export const Container = styled.div\`
transform: rotate(${'${props => props.$rotateDeg}'}deg);
width: ${'${size}'}px;
\`;
`,
[evaluator]
);
expect(code).toMatchSnapshot();
expect(metadata).toMatchSnapshot();
});
```
> test(shaker): add a failed test for issue 1141

- packages/babel/src/module.ts
Not an "issue", I saw this when trying to debug another issue, and it seemed wasteful.
No functionality change.
Ran `webpack`
> Skip creating new vm contexts when modules are already evaluated

- .changeset/sour-taxis-hear.md
- packages/babel/src/index.ts
- packages/babel/src/module.ts
- packages/babel/src/transform-stages/1-prepare-for-eval.ts
- packages/testkit/src/babel.test.ts
- packages/testkit/src/collectExportsAndImports.test.ts
- packages/testkit/src/module.test.ts
- packages/utils/src/asyncResolveFallback.ts
- packages/utils/src/collectExportsAndImports.ts
See #1209
A couple of new tests were added.
> fix(babel): modules being erroneously evaluated as empty objects (fixes #1209)

- README.md
Hi! Currently I am looking for the best css solution for me and I stumbled over linaria and also over this article here [https://medium.com/airbnb-engineering/airbnbs-trip-to-linaria-dc169230bd12](https://medium.com/airbnb-engineering/airbnbs-trip-to-linaria-dc169230bd12)
My question: I didn’t find a reference to this article within your docs and I ask myself “why?” because it’s great advertising for linaria and would probably bring more users, sponsors, and contributors?
I asked my question at the Discord channel and got asked by Michał Pierzchała if I could add the link to the docs.
I just added the link directly below "Why use Linaria" because I think this article is really great and everyone should read it on his or her journey of evaluating and picking a styling technology. The …
> docs: added reference to airbnb's article on linaria

- docs/CONFIGURATION.md
fyi I took ownership of the plugin a few years ago.
Resolves #777
> doc: Update gatsby plugin link

- .changeset/new-gorillas-shake.md
- packages/babel/src/transform-stages/helpers/loadLinariaOptions.ts
If `.cjs/.mjs` are supported, `.cts/.mts` should be supported too.
> feat(babel): add .cts, .mts to extension list

- .changeset/breezy-terms-march.md
- packages/babel/src/utils/collectTemplateDependencies.ts
- packages/react/src/processors/styled.ts
- packages/tags/src/types.ts
- packages/testkit/src/__fixtures__/linaria-ui-library/hocs.js
- packages/testkit/src/__snapshots__/babel.test.ts.snap
- packages/testkit/src/babel.test.ts
- packages/testkit/src/utils/getTagProcessor.test.ts
> fix(styled): enable #1276 optimisation for complex expressions

- .changeset/slow-apples-repeat.md
- docs/CONFIGURATION.md
- docs/FEATURE_FLAGS.md
- packages/babel/src/plugins/preeval.ts
- packages/babel/src/transform-stages/helpers/loadLinariaOptions.ts
- packages/testkit/src/preeval.test.ts
- packages/testkit/src/utils/isFeatureEnabled.test.ts
- packages/utils/package.json
- packages/utils/src/index.ts
- packages/utils/src/options/index.ts
- packages/utils/src/options/isFeatureEnabled.ts
- packages/utils/src/options/types.ts
- packages/utils/src/removeDangerousCode.ts
- pnpm-lock.yaml
Provide more control over the build and evaluation process.
See FEATURE_FLAGS.md
A bunch of new tests were added.
> feat: feature flags and configurable code remover

- README.md
Your current codesandbox example seems to be out of date. Since I happened to create one for testing purposes, I thought you might like to use it. :)
> docs: Update codesandbox example

- packages/testkit/src/__snapshots__/babel.test.ts.snap
- packages/testkit/src/babel.test.ts
Adds an additional test for #1374. Will pass once #1374 is merged.
> chore: add a snapshot for interpolation
